import type { DiscoveryLocale } from '../types/discovery'

const en = {
  explore: 'Explore gyms',
  back: 'Back',
  gym: 'Gym detail',
  equipment: 'Equipment',
  search: 'Search gyms by name or address',
  searchShort: 'Search gyms',
  searchEquipment: 'Search machines or exercises',
  clear: 'Clear',
  filters: 'Filters',
  reset: 'Reset',
  apply: 'Show gyms',
  any: 'Any',
  distance: 'Distance',
  rating: 'Rating',
  openNow: 'Open now',
  closed: 'Closed',
  supported: 'LIFTAG supported',
  manufacturers: 'Equipment brands',
  brandSearch: 'Find a brand',
  muscles: 'Muscle groups',
  locate: 'Locate me',
  locating: 'Finding your location…',
  locationDenied: 'Location is unavailable. You can still search and explore the map.',
  locationHint: 'Use Locate me to filter by distance.',
  globalSearch: 'Searching all gyms. Your filters resume when you clear search.',
  noGyms: 'No gyms here yet',
  noGymsHint: 'Move the map, search by name, or clear your filters.',
  loading: 'Loading…',
  loadError: 'This content could not be loaded.',
  retry: 'Try again',
  more: 'Show more',
  mapError: 'The map is unavailable right now.',
  mapErrorHint: 'You can still search gyms and open their details.',
  zoomIn: 'Zoom in to see more gyms in this area.',
  results: 'Gyms',
  viewGym: 'View gym',
  away: 'away',
  reviews: 'Reviews',
  noReviews: 'No reviews yet. Be the first to share your experience in LIFTAG.',
  rateGym: 'Rate this gym',
  hours: 'Opening hours',
  hoursUnknown: 'Opening hours have not been provided.',
  closedTemporarily: 'Temporarily closed',
  reopens: 'Reopens',
  gallery: 'Gym gallery',
  photos: 'Photos',
  previous: 'Previous',
  next: 'Next',
  close: 'Close',
  viewAllEquipment: 'View all equipment',
  noEquipment: 'This gym has not added its equipment yet.',
  noEquipmentMatch: 'No equipment matches these filters.',
  exercises: 'Exercises',
  brands: 'brands',
  generate: 'Generate a workout with AI',
  generateHint: 'Built around the equipment in this gym.',
  directions: 'Get directions',
  showOnMap: 'Show on map',
  trainers: 'Trainers',
  routines: 'Workouts',
  plans: 'Training plans',
  noRoutines: 'No public workouts yet.',
  noPlans: 'No public plans yet.',
  online: 'Online coaching',
  experience: 'years of experience',
  contact: 'Contact',
  affiliatedGyms: 'Gyms',
  about: 'About',
  startRoutine: 'Start workout',
  saveRoutine: 'Save',
  copyRoutine: 'Copy',
  rateRoutine: 'Rate',
  sets: 'Sets',
  set: 'Set',
  reps: 'Reps',
  weight: 'Weight',
  rest: 'Rest',
  duration: 'Duration',
  calories: 'Calories',
  notes: 'Notes',
  superset: 'Superset',
  rounds: 'rounds',
  instructions: 'Instructions',
  catalogExercise: 'View catalog exercise',
  noExercises: 'No exercises have been added yet.',
  appTitle: 'Continue in the LIFTAG app',
  appDownload: 'Download LIFTAG',
  appEyebrow: 'YOUR TRAINING PARTNER',
  appHeadlineLead: 'TAKE IT TO',
  appHeadlineTail: 'THE APP.',
  appScan: 'Scan with your phone camera.',
  appGenerate: 'Download LIFTAG to generate a workout using this gym’s equipment.',
  appReview: 'Download LIFTAG to rate this gym and write a review.',
  appRoutine: 'Download LIFTAG to start, save, copy, or rate this workout.',
  appPlan: 'Download LIFTAG to view and follow this training plan.',
  unavailable: 'This page is unavailable',
  unavailableHint: 'It may have been removed or is no longer public.',
  intro: 'Find your next training spot.',
  video: 'Video',
  noMedia: 'No photos yet',
  exerciseDetails: 'Exercise details',
  phone: 'Phone',
  email: 'Email',
  website: 'Website',
  minutes: 'min',
  seconds: 'sec',
  copies: 'copies',
  publicWorkout: 'Public workout',
  language: 'Language',
  map: 'Map',
  gymMachine: 'Gym machine',
  skip: 'Skip to content',
  planPreview: 'View in app',
  clearFilters: 'Clear filters',
  list: 'Gym list',
}
export type DiscoveryCopy = typeof en
const sk: DiscoveryCopy = {
  explore: 'Objavuj fitká',
  back: 'Späť',
  gym: 'Detail fitka',
  equipment: 'Vybavenie',
  search: 'Hľadať fitká podľa názvu alebo adresy',
  searchShort: 'Hľadať fitká',
  searchEquipment: 'Hľadať stroje alebo cviky',
  clear: 'Vymazať',
  filters: 'Filtre',
  reset: 'Obnoviť',
  apply: 'Zobraziť fitká',
  any: 'Všetky',
  distance: 'Vzdialenosť',
  rating: 'Hodnotenie',
  openNow: 'Otvorené',
  closed: 'Zatvorené',
  supported: 'Podporuje LIFTAG',
  manufacturers: 'Značky vybavenia',
  brandSearch: 'Hľadať značku',
  muscles: 'Svalové partie',
  locate: 'Moja poloha',
  locating: 'Zisťujeme tvoju polohu…',
  locationDenied: 'Poloha nie je dostupná. Stále môžeš vyhľadávať a prezerať mapu.',
  locationHint: 'Pre filter vzdialenosti povoľ svoju polohu.',
  globalSearch: 'Hľadáme vo všetkých fitkách. Filtre sa obnovia po vymazaní vyhľadávania.',
  noGyms: 'Zatiaľ tu nie sú žiadne fitká',
  noGymsHint: 'Posuň mapu, hľadaj podľa názvu alebo vymaž filtre.',
  loading: 'Načítava sa…',
  loadError: 'Tento obsah sa nepodarilo načítať.',
  retry: 'Skúsiť znova',
  more: 'Zobraziť viac',
  mapError: 'Mapa momentálne nie je dostupná.',
  mapErrorHint: 'Stále môžeš vyhľadávať fitká a otvoriť ich detaily.',
  zoomIn: 'Priblíž mapu a objav ďalšie fitká v tejto oblasti.',
  results: 'Fitká',
  viewGym: 'Detail fitka',
  away: 'od teba',
  reviews: 'Recenzie',
  noReviews: 'Zatiaľ žiadne recenzie. Podeľ sa o svoju skúsenosť v aplikácii LIFTAG.',
  rateGym: 'Ohodnotiť fitko',
  hours: 'Otváracie hodiny',
  hoursUnknown: 'Otváracie hodiny zatiaľ nie sú uvedené.',
  closedTemporarily: 'Dočasne zatvorené',
  reopens: 'Znovu otvorené',
  gallery: 'Galéria fitka',
  photos: 'Fotografie',
  previous: 'Predchádzajúca',
  next: 'Nasledujúca',
  close: 'Zavrieť',
  viewAllEquipment: 'Zobraziť celé vybavenie',
  noEquipment: 'Toto fitko zatiaľ nepridalo vybavenie.',
  noEquipmentMatch: 'Týmto filtrom nezodpovedá žiadne vybavenie.',
  exercises: 'Cviky',
  brands: 'značiek',
  generate: 'Vygenerovať tréning pomocou AI',
  generateHint: 'Tréning prispôsobený vybaveniu tohto fitka.',
  directions: 'Navigovať',
  showOnMap: 'Zobraziť na mape',
  trainers: 'Tréneri',
  routines: 'Tréningy',
  plans: 'Tréningové plány',
  noRoutines: 'Zatiaľ žiadne verejné tréningy.',
  noPlans: 'Zatiaľ žiadne verejné plány.',
  online: 'Online tréningy',
  experience: 'rokov skúseností',
  contact: 'Kontakt',
  affiliatedGyms: 'Fitká',
  about: 'O mne',
  startRoutine: 'Začať tréning',
  saveRoutine: 'Uložiť',
  copyRoutine: 'Kopírovať',
  rateRoutine: 'Ohodnotiť',
  sets: 'Série',
  set: 'Séria',
  reps: 'Opakovania',
  weight: 'Váha',
  rest: 'Pauza',
  duration: 'Trvanie',
  calories: 'Kalórie',
  notes: 'Poznámky',
  superset: 'Superséria',
  rounds: 'kolá',
  instructions: 'Pokyny',
  catalogExercise: 'Zobraziť cvik v katalógu',
  noExercises: 'Zatiaľ neboli pridané žiadne cviky.',
  appTitle: 'Pokračuj v aplikácii LIFTAG',
  appDownload: 'Stiahnuť LIFTAG',
  appEyebrow: 'TVOJ TRÉNINGOVÝ PARTNER',
  appHeadlineLead: 'POKRAČUJ V',
  appHeadlineTail: 'APLIKÁCII.',
  appScan: 'Naskenuj fotoaparátom v telefóne.',
  appGenerate: 'Stiahni si LIFTAG a vygeneruj tréning podľa vybavenia tohto fitka.',
  appReview: 'Stiahni si LIFTAG, ohodnoť toto fitko a napíš recenziu.',
  appRoutine: 'Stiahni si LIFTAG a začni, ulož, skopíruj alebo ohodnoť tento tréning.',
  appPlan: 'Stiahni si LIFTAG a pozri si celý tréningový plán.',
  unavailable: 'Táto stránka nie je dostupná',
  unavailableHint: 'Mohla byť odstránená alebo už nie je verejná.',
  intro: 'Nájdi svoje ďalšie fitko.',
  video: 'Video',
  noMedia: 'Zatiaľ bez fotografií',
  exerciseDetails: 'Detail cviku',
  phone: 'Telefón',
  email: 'E-mail',
  website: 'Web',
  minutes: 'min',
  seconds: 's',
  copies: 'kópií',
  publicWorkout: 'Verejný tréning',
  language: 'Jazyk',
  map: 'Mapa',
  gymMachine: 'Stroj vo fitku',
  skip: 'Preskočiť na obsah',
  planPreview: 'Otvoriť v aplikácii',
  clearFilters: 'Vymazať filtre',
  list: 'Zoznam fitiek',
}
export const discoveryCopy = (locale: DiscoveryLocale): DiscoveryCopy => (locale === 'sk' ? sk : en)
export const discoveryWeekdays = (locale: DiscoveryLocale): string[] =>
  locale === 'sk'
    ? ['Pondelok', 'Utorok', 'Streda', 'Štvrtok', 'Piatok', 'Sobota', 'Nedeľa']
    : ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
const specializationLabels: Record<string, string> = {
  bodybuilding: 'Kulturistika',
  weight_loss: 'Chudnutie',
  functional_training: 'Funkčný tréning',
  nutrition: 'Výživa',
  powerlifting: 'Silový trojboj',
  strength_training: 'Silový tréning',
  rehabilitation: 'Rehabilitácia',
  mobility: 'Mobilita',
  endurance: 'Vytrvalosť',
  calisthenics: 'Kalistenika',
  crossfit: 'CrossFit',
  sports_performance: 'Športový výkon',
  yoga: 'Joga',
  pilates: 'Pilates',
}
const levelLabels: Record<string, string> = {
  beginner: 'Začiatočník',
  intermediate: 'Pokročilý',
  advanced: 'Skúsený',
}
export function discoveryLabel(value: string, locale: DiscoveryLocale): string {
  const translated = specializationLabels[value] ?? levelLabels[value]
  if (locale === 'sk' && translated) return translated
  return value.replaceAll('_', ' ').replace(/^./, (c) => c.toUpperCase())
}

/** Slovak needs a third form for 5+; English only ever needs singular/plural. */
const countForms = {
  en: {
    exercises: ['exercise', 'exercises'],
    machines: ['equipment type', 'equipment types'],
    units: ['unit', 'units'],
    sets: ['set', 'sets'],
    reviews: ['review', 'reviews'],
  },
  sk: {
    exercises: ['cvik', 'cviky', 'cvikov'],
    machines: ['typ vybavenia', 'typy vybavenia', 'typov vybavenia'],
    units: ['kus', 'kusy', 'kusov'],
    sets: ['séria', 'série', 'sérií'],
    reviews: ['recenzia', 'recenzie', 'recenzií'],
  },
} as const

export function discoveryCount(
  count: number,
  kind: keyof (typeof countForms)['en'],
  locale: DiscoveryLocale,
): string {
  const forms = countForms[locale][kind]
  const index = locale === 'sk' ? (count === 1 ? 0 : count >= 2 && count <= 4 ? 1 : 2) : count === 1 ? 0 : 1
  return `${count.toLocaleString(locale)} ${forms[index]}`
}

/**
 * Ratings and distances render once per card in lists that are hundreds long,
 * so the formatters are built once per locale instead of once per value.
 */
const decimalFormats = new Map<DiscoveryLocale, Intl.NumberFormat>()
function decimalFormat(locale: DiscoveryLocale): Intl.NumberFormat {
  let format = decimalFormats.get(locale)
  if (!format) {
    format = new Intl.NumberFormat(locale, { maximumFractionDigits: 1 })
    decimalFormats.set(locale, format)
  }
  return format
}
export const discoveryRating = (value: number, locale: DiscoveryLocale): string =>
  decimalFormat(locale).format(value)
export const discoveryDistance = (km: number, locale: DiscoveryLocale): string =>
  `${decimalFormat(locale).format(km)} km`
