import type { JournalArticle } from './types'

const pubmed = 'https://pubmed.ncbi.nlm.nih.gov/42730852/'
const paper = 'https://link.springer.com/article/10.1007/s00421-026-06428-x'

export const en = {
  slug: 'velocity-based-hypertrophy-training', path: '/journal/velocity-based-hypertrophy-training',
  titleHtml: 'Does velocity-based training build <span class="lime">more chest?</span>',
  titleText: 'Does velocity-based training build more chest?',
  description: 'What bar-speed data can add to hypertrophy training, how to log it, and when a velocity sensor is worth using.',
  seoTitle: 'Velocity-Based Hypertrophy Training: New Study | LIFTAG',
  datePublished: '2026-10-07', category: 'RESEARCH', dateUpdated: '2026-10', citations: [pubmed, paper],
  body: `<section><h2>What the paper found</h2><p>Afonso Fitas, Miguel Gomes, Agustín Valdés-Álvarez, Sergio Miras-Moreno, Caetano Cardoso, Pedro Pezarat Correia and Goncalo V. Mendonca compared velocity-based and percentage-based bench training in 19 trained men for ten weeks. The 2026 <em>European Journal of Applied Physiology</em> paper reports similar increases in pectoralis size and bench 1RM, with no statistically distinct VBT advantage. This small experiment does not prove the methods equivalent or cover every use of velocity feedback.</p></section>
<section><h2>What the number actually adds</h2><p>Percentage training uses a prior maximum as its anchor. VBT measures today’s rep and can inform a load adjustment. That changes how a session is managed, but it does not create a new training stimulus by itself. Muscles still experience the load, repetitions, range, effort and fatigue produced by the prescription.</p><p>The useful question is therefore not whether velocity is “better” in the abstract. Ask whether seeing it changes a decision: selecting today’s load, ending a set, protecting technique or keeping intent consistent. If the number never changes an action, it is extra data rather than extra coaching.</p></section>
<section><h2>What VBT still does well</h2><p>A velocity device can show whether a warm-up load is moving slower than usual, standardize an intent to lift fast and provide immediate feedback. Coaches can use velocity loss to control fatigue or a load–velocity profile to estimate readiness. Those are operational benefits even when the device does not add muscle.</p><p>The study challenges a stronger sales pitch: that autoregulating bench load from velocity necessarily creates superior hypertrophy or 1RM gains. Here, a well-run percentage program produced similar measured changes. A bar-speed number is information, not an anabolic ingredient.</p><p>There is also a cost question. If a device, setup and calibration make training easier to coach or more engaging, the value can be real. If the only goal is chest growth, this study gives no clear reason to treat the device as required equipment.</p></section>
<section><h2>Run a sensor trial before buying the story</h2><p>If you can borrow a device, decide in advance how it will affect training. Set a rule such as reducing the load when warm-up velocity falls outside your normal range, or ending a set after a chosen drop. Then record whether the rule changed loads, repetitions or session duration. A month of unused readings is evidence that the tool does not yet solve a problem for you.</p><p>Consistency matters more than collecting every possible metric. Use the same sensor position, exercise setup and velocity definition. Compare similar loads and avoid interpreting tiny day-to-day differences as readiness. A measurement is useful when it is repeatable enough to support a decision and simple enough that you will keep taking it.</p></section>
<section><h2>A useful logging approach</h2><p>Most lifters can capture the variables that matter without a velocity sensor: exercise, load, repetitions, sets and proximity to failure. Keep the bench setup and range of motion consistent. Review whether the same load produces more reps at a comparable RPE, or whether a heavier load becomes repeatable for the same reps.</p><p>If you do use VBT, log velocity beside those basics rather than replacing them. Mark whether the value is mean or peak velocity, which device measured it and whether the rep was concentric-only or included another definition. Device and protocol changes can make a clean-looking trend meaningless.</p><p>Judge the method across a block, not from one slow day. Sleep, motivation, technique and measurement error all move bar speed. The most defensible reading of this paper is that VBT is an optional prescription tool: useful for some decisions, but not demonstrated here as a superior route to hypertrophy or maximal strength.</p><p>Read the <a href="${pubmed}">PubMed record</a> and the <a href="${paper}">publisher’s article</a>. The full paper is subscription content and Springer states that it holds exclusive rights; this is independent commentary, not a reproduction. The authors named above receive full credit for the study. Links were checked on 7 October 2026.</p></section>`,
  faqs: [
    { question: 'Do I need VBT to build muscle?', answer: 'No. A sensor may help guide loads and fatigue, but muscle growth still depends on the training you perform and recover from.' },
    { question: 'What should I record with bar velocity?', answer: 'Keep exercise, load, reps, effort and setup alongside velocity. Also record the device, metric definition and the decision the reading caused.' },
    { question: 'Is a velocity sensor useless?', answer: 'No. It can support readiness checks, feedback and fatigue management. This study only found no clear extra hypertrophy or maximal-strength benefit in its specific protocol.' },
  ],
  ctaPath: '/', ctaLabel: 'Track your training with LIFTAG', secondaryPath: '/journal', secondaryLabel: 'Read more research',
} satisfies JournalArticle

export const sk = {
  slug: 'velocity-based-hypertrophy-training', path: '/journal/velocity-based-hypertrophy-training',
  titleHtml: 'Vybuduje tréning podľa rýchlosti <span class="lime">väčší hrudník?</span>',
  titleText: 'Vybuduje tréning podľa rýchlosti väčší hrudník?',
  description: 'Čo môže rýchlosť činky pridať k tréningu hypertrofie, ako ju zapisovať a kedy sa oplatí používať snímač.',
  seoTitle: 'Tréning hypertrofie podľa rýchlosti: nová štúdia | LIFTAG',
  datePublished: '2026-10-07', category: 'VÝSKUM', dateUpdated: '2026-10', citations: [pubmed, paper],
  body: `<section><h2>Čo práca zistila</h2><p>Afonso Fitas, Miguel Gomes, Agustín Valdés-Álvarez, Sergio Miras-Moreno, Caetano Cardoso, Pedro Pezarat Correia a Goncalo V. Mendonca porovnali desať týždňov bencha podľa rýchlosti a podľa percent u 19 trénovaných mužov. Článok z roku 2026 v <em>European Journal of Applied Physiology</em> uvádza podobné zväčšenie prsného svalu a nárast 1RM bez štatisticky jasnej výhody VBT. Malý experiment nedokazuje rovnocennosť metód ani nepokrýva všetky použitia spätnej väzby.</p></section>
<section><h2>Čo číslo skutočne pridáva</h2><p>Percentuálny tréning sa opiera o predchádzajúce maximum. VBT zmeria dnešné opakovanie a môže ovplyvniť voľbu záťaže. Mení riadenie tréningu, ale samo osebe nevytvára nový stimul. Sval stále zažíva záťaž, opakovania, rozsah, úsilie a únavu z konkrétneho predpisu.</p><p>Užitočná otázka preto neznie, či je rýchlosť všeobecne „lepšia“. Pýtaj sa, či údaj zmení rozhodnutie: dnešnú záťaž, ukončenie série, ochranu techniky alebo konzistentný úmysel dvíhať rýchlo. Ak údaj nikdy nezmení konanie, je to viac dát, nie viac koučingu. Aj dobrý údaj potrebuje vopred dohodnuté pravidlo, inak ho ľahko vysvetlíš podľa nálady až po tréningu.</p></section>
<section><h2>V čom môže byť VBT užitočné</h2><p>Zariadenie na meranie rýchlosti môže ukázať, či sa rozcvičovacia váha hýbe pomalšie než zvyčajne, štandardizovať úmysel dvíhať rýchlo a poskytnúť okamžitú spätnú väzbu. Tréner môže využiť stratu rýchlosti na kontrolu únavy alebo profil záťaž–rýchlosť na odhad pripravenosti. Sú to praktické výhody aj bez dodatočného rastu svalov.</p><p>Štúdia spochybňuje silnejší marketingový sľub, že autoregulácia bencha podľa rýchlosti nevyhnutne prináša lepšiu hypertrofiu alebo väčší nárast 1RM. Dobre vedený percentuálny program tu vytvoril podobné merané zmeny. Rýchlosť činky je informácia, nie anabolická zložka.</p><p>Záleží aj na cene. Ak zariadenie, nastavenie a kalibrácia uľahčia vedenie tréningu alebo zvýšia motiváciu, môžu mať reálnu hodnotu. Ak je jediným cieľom rast hrudníka, táto štúdia nedáva jasný dôvod považovať snímač za povinnú výbavu.</p></section>
<section><h2>Pred kúpou si otestuj použitie</h2><p>Ak si vieš zariadenie požičať, vopred urči, ako má ovplyvniť tréning. Nastav pravidlo: znížiť váhu, keď rýchlosť rozcvičovacej série vybočí z tvojho bežného pásma, alebo ukončiť sériu po zvolenom poklese. Potom zapisuj, či pravidlo zmenilo záťaž, opakovania alebo dĺžku tréningu. Mesiac nepoužitých hodnôt je dôkaz, že nástroj zatiaľ nerieši tvoj problém.</p><p>Dôležitejšia než zber všetkých metrík je konzistentnosť. Zachovaj polohu snímača, nastavenie cviku a definíciu rýchlosti. Porovnávaj podobné záťaže a malé denné rozdiely automaticky nevyhlasuj za zmenu pripravenosti. Meranie má hodnotu, keď je dostatočne opakovateľné na rozhodovanie a dosť jednoduché na pravidelné používanie.</p></section>
<section><h2>Ako si tréning zapisovať</h2><p>Väčšina ľudí zachytí dôležité premenné aj bez snímača: cvik, záťaž, opakovania, série a blízkosť zlyhania. Drž rovnaké nastavenie bencha a rozsah pohybu. Sleduj, či pri porovnateľnom RPE spravíš s rovnakou váhou viac opakovaní alebo či vyššia váha začne byť opakovateľná.</p><p>Ak VBT používaš, zapisuj rýchlosť vedľa základov, nie namiesto nich. Označ, či ide o priemernú alebo maximálnu rýchlosť, aké zariadenie ju meralo a akú definíciu opakovania používa. Zmena zariadenia či protokolu môže znehodnotiť aj pekne vyzerajúci trend.</p><p>Metódu hodnoť cez celý blok, nie podľa jedného pomalého dňa. Rýchlosť mení spánok, motivácia, technika aj chyba merania. Najobhájiteľnejší záver je, že VBT je voliteľný nástroj na predpis: pri niektorých rozhodnutiach užitočný, ale v tejto štúdii nebol preukázaný ako lepšia cesta k hypertrofii alebo maximálnej sile.</p><p>Do poznámky pridaj aj rozhodnutie, ktoré z merania vzniklo. Samotné číslo o rok neskôr nevysvetlí, prečo si znížil váhu alebo ukončil sériu. Krátky záznam „rozcvička pomalšia, mínus päť kilogramov“ spája údaj s konaním. Tak zistíš, či pravidlá vedú k rozumnejším tréningom, alebo iba vytvárajú ďalší stĺpec, ktorý prestaneš sledovať.</p><p>Prečítaj si <a href="${pubmed}">záznam na PubMed</a> a <a href="${paper}">článok vydavateľa</a>. Celý článok je platený a Springer uvádza, že k nemu drží výhradné práva; toto je nezávislý komentár, nie reprodukcia. Všetkým vyššie uvedeným autorom patrí plná zásluha za štúdiu. Odkazy boli overené 7. októbra 2026.</p></section>`,
  faqs: [
    { question: 'Potrebujem VBT na rast svalov?', answer: 'Nie. Snímač môže pomôcť riadiť záťaž a únavu, ale rast stále závisí od tréningu, ktorý vykonáš a z ktorého sa zregeneruješ.' },
    { question: 'Čo zapisovať spolu s rýchlosťou činky?', answer: 'Zachovaj cvik, záťaž, opakovania, úsilie a nastavenie. Zapíš aj zariadenie, definíciu metriky a rozhodnutie, ktoré údaj vyvolal.' },
    { question: 'Je snímač rýchlosti zbytočný?', answer: 'Nie. Môže pomôcť s odhadom pripravenosti, spätnou väzbou a únavou. Táto štúdia len nenašla jasný dodatočný prínos pre hypertrofiu alebo maximálnu silu vo svojom protokole.' },
  ],
  ctaPath: '/', ctaLabel: 'Zapisovať tréning v LIFTAG', secondaryPath: '/journal', secondaryLabel: 'Čítať ďalší výskum',
} satisfies typeof en
