import type { JournalArticle } from './types'

const pubmed = 'https://pubmed.ncbi.nlm.nih.gov/42730852/'
const paper = 'https://link.springer.com/article/10.1007/s00421-026-06428-x'

export const en = {
  slug: 'velocity-based-hypertrophy-training', path: '/journal/velocity-based-hypertrophy-training',
  titleHtml: 'Does tracking bar speed help build <span class="lime">chest muscle?</span>',
  titleText: 'Does tracking bar speed help build chest muscle?',
  description: 'What bar-speed data can add to muscle-building workouts, what belongs in the log, and what this small bench-press study can tell us.',
  seoTitle: 'Velocity-Based Hypertrophy Training: New Study | LIFTAG',
  datePublished: '2026-10-07', category: 'RESEARCH', dateUpdated: '2026-10', citations: [pubmed, paper],
  body: `<section><h2>The short answer</h2><p>Fitas and colleagues studied 19 trained men benching for ten weeks. Bar-speed loading did not produce significantly better chest growth or strength than percentage loading. The small study found no superiority; it did not prove the methods equal.</p></section>
<section><h2>What VBT measures</h2><p>Velocity-based training, usually shortened to VBT, measures how fast the bar moves. A sensor might show that a warm-up rep moved at 0.55 metres per second today. The program can then use that reading when choosing the work weight.</p><p>Percentage-based training starts somewhere else. It takes your known or estimated one-rep maximum (1RM), the most weight you can lift once, and prescribes a share of it, such as 70%. The number is easy to use, but it may come from a test done weeks ago. VBT adds information from the current session.</p><p>That information can change a decision, but the reading itself does not train the chest. The work still comes from the bench press: the load, reps, range of motion and effort that the lifter completes.</p></section>
<section><h2>A number needs a job</h2><p>Bar speed is most useful when everyone knows what happens next. A coach may use it to choose the day’s load, check whether the lifter is moving with full intent, or stop a set after speed falls by a chosen amount.</p><p>Without a rule, the screen can fill with numbers that never affect the workout. A reading of 0.48 means little on its own. Was it the average speed of the rep or its fastest point? Which sensor measured it? Was the pause on the chest the same? Was the load 80 kg both times? Those details decide whether two readings can be compared.</p><p>The same applies to a slow day. Sleep, setup, technique and measurement error can all move the result. One unusually slow warm-up is a note in the log, not a complete verdict on readiness.</p></section>
<section><h2>What a speed trace can show</h2><p>A normal workout entry gives the result: 80 kg for eight reps. A speed trace adds the shape of the set. The early reps may move at a similar pace before the last two slow sharply. Another set with the same weight and reps may slow gradually from the start. On paper they match; on the sensor they do not.</p><p>That extra detail is the main appeal. It can make fatigue inside a set visible and give two people a shared reference when discussing the rep. It still needs the ordinary entry beside it. Without the weight, reps and exercise setup, the speed trace has very little context.</p></section>
<section><h2>Keep the ordinary workout data</h2><p>A velocity sensor should add a field to the log, not replace the basics. Exercise, weight, sets, reps and effort still explain what training was done. On the bench press, the grip, pause and range of motion also need to stay recognizable if the history is going to mean anything.</p><p>Consider two entries: “80 kg × 8” and “80 kg × 8, last rep 18% slower.” The second tells you more about how the set unfolded. But if the next session uses a different sensor or switches from mean to peak velocity, the neat graph may compare two different measurements.</p><p>Record the decision as well as the reading. “Warm-up slower, reduced work sets by 5 kg” explains why the plan changed. Months later, that short note is more useful than a column of speeds with no connection to an action.</p></section>
<section><h2>What this study can answer</h2><p>For this ten-week bench program, velocity-based loading did not show better muscle or strength results than percentage-based loading. That is a useful check on the idea that more measurement must lead to more growth.</p><p>It does not make a sensor pointless. Bar speed may still help with feedback or with running a rule consistently. It also does not prove the two methods always work equally well. Nineteen people leave plenty of room for smaller differences that this experiment could not detect.</p><p>Source: Afonso Fitas, Miguel Gomes, Agustín Valdés-Álvarez, Sergio Miras-Moreno, Caetano Cardoso, Pedro Pezarat Correia and Goncalo V. Mendonca, “Effects of velocity-based hypertrophy training on pectoralis major morphology, neuromuscular activation and bench press maximal strength,” <em>European Journal of Applied Physiology</em>, published 12 September 2026. Read the <a href="${pubmed}">PubMed record</a> or the <a href="${paper}">publisher’s page</a>. Links checked 7 October 2026.</p></section>`,
  faqs: [
    { question: 'Does tracking bar speed help build chest muscle?', answer: 'The study found no clear chest-growth advantage from choosing weights using bar speed. It was too small and short to prove the methods work equally well.' },
    { question: 'What should I record with bar speed?', answer: 'Keep the exercise, weight, reps, effort and setup beside the speed. Also record the device, whether it shows the average speed of the rep or its fastest point, and any decision the reading changed.' },
    { question: 'Is a bar-speed sensor useless?', answer: 'No. It can provide feedback and show how speed falls within a set. This study simply found no clear extra muscle-growth or maximum-strength benefit in its bench program.' },
  ],
  ctaPath: '/', ctaLabel: 'Track your training with LIFTAG', secondaryPath: '/journal', secondaryLabel: 'Read more research',
} satisfies JournalArticle

export const sk = {
  slug: 'velocity-based-hypertrophy-training', path: '/journal/velocity-based-hypertrophy-training',
  titleHtml: 'Pomáha meranie rýchlosti činky <span class="lime">pri raste prsných svalov?</span>',
  titleText: 'Pomáha meranie rýchlosti činky pri raste prsných svalov?',
  description: 'Čo môže rýchlosť činky pridať k tréningu na rast svalov, čo patrí do denníka a čo nám povie malá štúdia bench pressu.',
  seoTitle: 'Tréning hypertrofie podľa rýchlosti: nová štúdia | LIFTAG',
  datePublished: '2026-10-07', category: 'VÝSKUM', dateUpdated: '2026-10', citations: [pubmed, paper],
  body: `<section><h2>Krátka odpoveď</h2><p>Fitas a kolektív sledovali 19 trénovaných mužov pri benchi počas desiatich týždňov. Nastavenie váhy podľa rýchlosti neprinieslo významne lepší rast hrudníka ani sily než percentá. Malá štúdia nenašla nadradenosť; nedokázala rovnocennosť metód.</p></section>
<section><h2>Čo VBT meria</h2><p>Tréning podľa rýchlosti, skrátene VBT, meria, ako rýchlo sa činka pohybuje. Snímač môže ukázať, že dnešné rozcvičovacie opakovanie išlo rýchlosťou 0,55 metra za sekundu. Program potom môže tento údaj použiť pri voľbe pracovnej váhy.</p><p>Percentuálny tréning začína inde. Zoberie známe alebo odhadnuté maximum na jedno opakovanie (1RM), teda najvyššiu váhu, ktorú zdvihneš raz, a predpíše jeho časť, napríklad 70 %. Číslo sa používa jednoducho, ale môže pochádzať z testu starého niekoľko týždňov. VBT pridáva informáciu z dnešného tréningu.</p><p>Táto informácia môže zmeniť rozhodnutie, no samotný údaj hrudník netrénuje. Prácu stále robí bench press: váha, opakovania, rozsah pohybu a úsilie, ktoré človek skutočne zvládne.</p></section>
<section><h2>Číslo potrebuje úlohu</h2><p>Rýchlosť činky je najužitočnejšia, keď každý vie, čo po meraní nasleduje. Tréner podľa nej môže vybrať dnešnú váhu, skontrolovať snahu dvíhať naplno alebo ukončiť sériu po vopred určenom poklese rýchlosti.</p><p>Bez pravidla sa obrazovka zaplní číslami, ktoré tréning nijako nezmenia. Hodnota 0,48 sama osebe povie málo. Išlo o priemernú rýchlosť opakovania alebo jeho najrýchlejší bod? Aký snímač ju meral? Bola pauza na hrudníku rovnaká? Bolo na činke zakaždým 80 kg? Od týchto detailov závisí, či dve hodnoty možno porovnať.</p><p>Platí to aj pre pomalý deň. Výsledok mení spánok, nastavenie lavičky, technika aj chyba merania. Jedna nezvyčajne pomalá rozcvička je poznámka v denníku, nie úplný rozsudok nad pripravenosťou.</p></section>
<section><h2>Čo ukáže priebeh rýchlosti</h2><p>Bežný zápis zachytí výsledok: 80 kg na osem opakovaní. Priebeh rýchlosti pridá tvar série. Prvé opakovania sa môžu hýbať podobne a posledné dve prudko spomalia. Iná séria s rovnakou váhou a počtom opakovaní môže spomaľovať postupne od začiatku. Na papieri sa zhodujú, na snímači nie.</p><p>Práve tento detail je hlavnou príťažlivosťou merania. Dokáže zviditeľniť únavu vo vnútri série a dá trénerovi s cvičencom spoločný bod pri rozhovore o opakovaní. Stále však potrebuje bežný zápis vedľa seba. Bez váhy, opakovaní a nastavenia cviku samotný priebeh rýchlosti veľa nevysvetlí.</p></section>
<section><h2>Základné údaje v denníku zostávajú</h2><p>Snímač rýchlosti má pridať políčko, nie nahradiť základy. Cvik, váha, série, opakovania a úsilie stále vysvetľujú, aký tréning prebehol. Pri benchi musí zostať rozpoznateľný aj úchop, pauza a rozsah pohybu, inak história stráca význam. Samotná rýchlosť bez názvu cviku a váhy nevysvetľuje takmer nič.</p><p>Porovnaj dva zápisy: „80 kg × 8“ a „80 kg × 8, posledné opakovanie o 18 % pomalšie“. Druhý prezradí viac o priebehu série. Ak však nabudúce použiješ iný snímač alebo prejdeš z priemernej na maximálnu rýchlosť, pekný graf môže porovnávať dve odlišné merania. Čísla vyzerajú presne, no ich význam závisí od rovnakého spôsobu zberu.</p><p>Zapíš aj rozhodnutie, nielen hodnotu. „Rozcvička pomalšia, pracovná váha o 5 kg nižšia“ vysvetlí, prečo sa plán zmenil. O niekoľko mesiacov pomôže krátka poznámka viac než stĺpec rýchlostí bez súvisu s konaním.</p></section>
<section><h2>Na čo táto štúdia odpovedá</h2><p>V tomto desaťtýždňovom programe na bench neprinieslo nastavovanie váhy podľa rýchlosti lepší rast svalov ani sily než nastavovanie podľa percent. Je to užitočná kontrola predstavy, že viac merania musí automaticky znamenať väčší rast.</p><p>Snímač tým nie je zbytočný. Rýchlosť môže pomôcť so spätnou väzbou alebo s dôsledným používaním pravidla. Štúdia tiež nedokazuje, že obe metódy vždy fungujú rovnako. Devätnásť ľudí ponecháva veľký priestor pre menšie rozdiely, ktoré experiment nemusel zachytiť.</p><p>Zdroj: Afonso Fitas, Miguel Gomes, Agustín Valdés-Álvarez, Sergio Miras-Moreno, Caetano Cardoso, Pedro Pezarat Correia a Goncalo V. Mendonca, „Effects of velocity-based hypertrophy training on pectoralis major morphology, neuromuscular activation and bench press maximal strength“, <em>European Journal of Applied Physiology</em>, zverejnené 12. septembra 2026. Pozri si <a href="${pubmed}">záznam na PubMed</a> alebo <a href="${paper}">stránku vydavateľa</a>. Odkazy overené 7. októbra 2026.</p></section>`,
  faqs: [
    { question: 'Pomáha meranie rýchlosti činky pri raste prsných svalov?', answer: 'Štúdia nenašla jasnú výhodu pre rast prsných svalov pri výbere váhy podľa rýchlosti činky. Bola príliš malá a krátka na to, aby dokázala, že obe metódy fungujú rovnako.' },
    { question: 'Čo zapisovať spolu s rýchlosťou činky?', answer: 'Zachovaj cvik, váhu, opakovania, úsilie a nastavenie. Zapíš aj zariadenie, či ukazuje priemernú rýchlosť opakovania alebo jeho najrýchlejší bod, a rozhodnutie, ktoré údaj zmenil.' },
    { question: 'Je snímač rýchlosti zbytočný?', answer: 'Nie. Môže poskytnúť spätnú väzbu a ukázať spomaľovanie v sérii. Táto štúdia len nenašla jasný dodatočný prínos pre rast svalov alebo maximálnu silu.' },
  ],
  ctaPath: '/', ctaLabel: 'Zapisovať tréning v LIFTAG', secondaryPath: '/journal', secondaryLabel: 'Čítať ďalší výskum',
} satisfies typeof en
