import type { JournalArticle } from './types'

const pubmed = 'https://pubmed.ncbi.nlm.nih.gov/42709978/'
const doi = 'https://doi.org/10.1519/JSC.0000000000005665'

export const en = {
  slug: 'weekly-set-distribution',
  path: '/journal/weekly-set-distribution',
  titleHtml: 'One long leg day or <span class="lime">three short ones?</span>',
  titleText: 'One long leg day or three short ones?',
  description: 'How to decide whether your weekly sets belong in one long session or several shorter workouts, using your own training log.',
  seoTitle: 'Weekly Set Distribution: 1 vs 3 Training Days | LIFTAG',
  datePublished: '2026-10-07',
  category: 'RESEARCH',
  dateUpdated: '2026-10',
  citations: [pubmed, doi],
  body: `<section><h2>What the paper found</h2><p>In a 2026 <em>Journal of Strength and Conditioning Research</em> study, Jader Calzavara and Renato Barroso assigned 18 trained men to six weeks of lower-body work. Both groups used the same loads and weekly sets; one completed them in one session and the other across three. Spreading the sets produced substantially more squat and leg-press volume load, while neither strength nor quadriceps thickness showed a statistically clear between-group advantage. A small, short study cannot prove the schedules equivalent.</p></section>
<section><h2>Volume load is a record, not a verdict</h2><p>Volume load multiplies weight by completed repetitions. It describes work done, but it cannot tell whether a rep used the same range, technique or effort. A large total may come from useful hard repetitions, easier repetitions, or simply an exercise whose numbers are large.</p><p>That makes the metric most valuable inside one person’s stable program. Compare the same movement, execution and effort target over time. Treat changes as clues that help explain performance, not as a universal score that ranks every workout.</p></section>
<section><h2>What a training log should capture</h2><p>If you want to test set distribution in your own plan, log more than a weekly set total. Keep the exercise, load, repetitions, rest time and effort target consistent enough to compare. For sets taken to failure, watch whether repetitions collapse from set one to set three. If they do, spreading the work may let you perform more quality repetitions.</p><p>For example, three squat sets recorded as 100 kg × 10, 8 and 6 produce less volume load than three separate fresh sets of 100 kg × 10. That is useful information, but it is not a muscle-growth score. Technique, range of motion, proximity to failure, recovery and the muscle being trained still matter.</p><p>Use a four-to-six-week block and compare trends: performance on the same exercise, estimated effort, soreness that affects later sessions, and whether the schedule is sustainable. Avoid changing frequency, exercise selection and loads at the same time, because the log will no longer tell you which change mattered.</p></section>
<section><h2>Choose frequency by its downstream cost</h2><p>An extra session has effects beyond the target muscle. It adds travel, setup, warm-ups and another appointment that can be missed. It can also shorten each visit, preserve attention for later exercises and make demanding sets feel safer. Neither side appears in a simple sets-per-week cell.</p><p>Before changing the split, write down the problem you want to solve. “My third squat set loses four reps” is testable. “Higher frequency is optimal” is too vague. Pick one success measure, such as keeping all work sets within two repetitions, and one cost measure, such as total weekly gym time. After a month, the decision becomes a comparison between outcomes you actually value.</p><p>Frequency also interacts with exercise choice. A hard squat may create more whole-body fatigue than a leg extension even when both count as one quadriceps set. Schedule the movements that need the most skill and stability when you are fresh, then place less demanding work where it fits. The calendar should serve execution, rather than forcing every exercise into identical frequency.</p></section>
<section><h2>How to use the result</h2><p>Spreading sets is a reasonable option when later sets deteriorate, sessions become too long, or lower-body fatigue compromises other exercises. Consolidating them remains reasonable when three gym visits are impractical. The paper does not support turning three weekly sets into three mandatory trips for everyone.</p><p>The strongest practical finding is narrower: distribution changes the work you can perform even when the written prescription says the same load and number of sets. This is why a useful workout history stores completed repetitions rather than calling two programs “volume matched” from the plan alone.</p><p>Credit belongs to Calzavara and Barroso for testing that distinction directly. Read the <a href="${pubmed}">PubMed record</a> or follow the <a href="${doi}">paper DOI</a>. Links and publication details were checked on 7 October 2026.</p></section>`,
  faqs: [
    { question: 'Is training a muscle three times per week always better than once?', answer: 'No. Choose a frequency that preserves good execution, recovery and consistency. Several shorter sessions can help when performance collapses late in a long workout.' },
    { question: 'Is volume load the same as training quality?', answer: 'No. It records load multiplied by repetitions, but cannot capture range of motion, technique, proximity to failure or which muscle did the work.' },
    { question: 'What should I log when comparing schedules?', answer: 'Record exercise, load, completed reps, rest time and proximity to failure. Compare several weeks under stable conditions rather than judging one workout.' },
  ],
  ctaPath: '/', ctaLabel: 'Track your training with LIFTAG', secondaryPath: '/journal', secondaryLabel: 'Read more research',
} satisfies JournalArticle

export const sk = {
  slug: 'weekly-set-distribution',
  path: '/journal/weekly-set-distribution',
  titleHtml: 'Jeden dlhý tréning nôh alebo <span class="lime">tri krátke?</span>',
  titleText: 'Jeden dlhý tréning nôh alebo tri krátke?',
  description: 'Ako podľa vlastného tréningového denníka rozhodnúť, či týždenné série patria do jedného dlhého alebo viacerých kratších tréningov.',
  seoTitle: 'Rozdelenie sérií: 1 alebo 3 tréningové dni | LIFTAG',
  datePublished: '2026-10-07', category: 'VÝSKUM', dateUpdated: '2026-10', citations: [pubmed, doi],
  body: `<section><h2>Čo práca zistila</h2><p>V štúdii z roku 2026 v <em>Journal of Strength and Conditioning Research</em> rozdelili Jader Calzavara a Renato Barroso 18 trénovaných mužov na šesť týždňov tréningu nôh. Obe skupiny mali rovnaké záťaže a týždenné série; jedna ich spravila v jednom tréningu, druhá v troch. Rozloženie prinieslo podstatne vyššiu objemovú záťaž v drepe a leg presse, no sila ani hrúbka kvadricepsu neukázali štatisticky jasnú výhodu jednej skupiny. Malá, krátka štúdia nedokazuje rovnocennosť rozvrhov.</p></section>
<section><h2>Objemová záťaž je záznam, nie rozsudok</h2><p>Objemová záťaž násobí váhu dokončenými opakovaniami. Opisuje vykonanú prácu, ale nerozozná rovnaký rozsah pohybu, techniku ani úsilie. Vysoké číslo môže pochádzať z hodnotných náročných opakovaní, ľahkých opakovaní alebo jednoducho z cviku s veľkými váhami.</p><p>Najväčšiu hodnotu má preto v stabilnom programe jedného človeka. Porovnávaj rovnaký pohyb, prevedenie a cieľové úsilie v čase. Zmeny ber ako stopy vysvetľujúce výkon, nie ako univerzálne skóre tréningu. Samostatné číslo bez kontextu často klame.</p></section>
<section><h2>Čo si zapisovať</h2><p>Ak chceš rozdelenie sérií otestovať vo vlastnom pláne, zapisuj viac než ich týždenný súčet. Cvik, záťaž, opakovania, prestávku a cieľové úsilie drž natoľko stabilné, aby sa dali porovnať. Pri sériách do zlyhania sleduj, či počet opakovaní od prvej po tretiu prudko neklesá. Ak áno, rozdelenie práce môže priniesť viac kvalitných opakovaní.</p><p>Tri série drepu 100 kg × 10, 8 a 6 vytvoria menšiu objemovú záťaž než tri samostatné čerstvé série 100 kg × 10. Je to užitočný údaj, ale nie skóre rastu svalov. Stále záleží na technike, rozsahu pohybu, blízkosti zlyhania, regenerácii a na tom, ktorý sval pracuje.</p><p>Porovnaj štvor- až šesťtýždňové bloky: výkon v rovnakom cviku, odhad náročnosti, bolesť ovplyvňujúcu ďalšie tréningy a udržateľnosť rozvrhu. Nemeň súčasne frekvenciu, výber cvikov aj záťaže, inak záznam neukáže, ktorá zmena zavážila.</p></section>
<section><h2>Frekvenciu vyberaj podľa celkovej ceny</h2><p>Ďalší tréning ovplyvní viac než cieľový sval. Pridáva cestu, prípravu, rozcvičenie a ďalší termín, ktorý môžeš vynechať. Zároveň môže skrátiť jednotlivé návštevy, zachovať sústredenie na neskoršie cviky a spraviť náročné série bezpečnejšími. V jednoduchom políčku „série za týždeň“ sa nič z toho neukáže.</p><p>Pred zmenou splitu si zapíš problém, ktorý riešiš. „V tretej sérii drepu strácam štyri opakovania“ sa dá otestovať. „Vyššia frekvencia je optimálna“ je príliš nejasné. Vyber jedno meradlo úspechu, napríklad udržať pracovné série v rozdiele dvoch opakovaní, a jedno meradlo ceny, napríklad celkový čas v posilňovni. Po mesiaci porovnáš výsledky, na ktorých ti naozaj záleží.</p><p>Frekvencia sa spája aj s výberom cvikov. Náročný drep môže vytvoriť väčšiu celkovú únavu než predkopávanie, hoci oba započítaš ako jednu sériu na kvadriceps. Pohyby vyžadujúce najviac techniky a stability plánuj na čas, keď si čerstvý. Menej náročnú prácu umiestni tam, kde sa zmestí. Kalendár má podporovať kvalitné prevedenie, nie nútiť každý cvik do rovnakej frekvencie.</p></section>
<section><h2>Ako výsledok použiť</h2><p>Rozloženie sérií dáva zmysel, keď sa neskoršie série rozpadajú, tréning je príliš dlhý alebo únava nôh kazí ďalšie cviky. Spojenie do jedného dňa zostáva rozumné, ak tri návštevy posilňovne nezapadajú do života. Táto práca nehovorí, že tri týždenné série vyžadujú tri povinné tréningy.</p><p>Najsilnejší praktický výsledok je užší: rozloženie mení prácu, ktorú dokážeš vykonať, aj keď plán uvádza rovnakú záťaž a počet sérií. Užitočná história tréningu preto uchováva skutočne dokončené opakovania. Zároveň si poznač vynechané tréningy: teoreticky lepší trojdňový rozvrh nepomôže, ak ho tvoj kalendár pravidelne rozbije.</p><p>Pri hodnotení nečakaj, že každý týždeň bude lepší. Jedna slabšia séria po zlom spánku nie je dôvod na prestavbu plánu. Hľadaj opakujúci sa vzorec v rovnakom cviku a podobnej intenzite. Ak rozdelenie sérií zlepší výkon, ale zhorší pravidelnosť alebo regeneráciu iných tréningov, výsledok nie je automaticky výhra.</p><p>Zásluha za priame otestovanie patrí Calzavarovi a Barrosovi. Pozri si <a href="${pubmed}">záznam na PubMed</a> alebo <a href="${doi}">DOI článku</a>. Odkazy a údaje boli overené 7. októbra 2026.</p></section>`,
  faqs: [
    { question: 'Je tréning svalu trikrát týždenne vždy lepší než raz?', answer: 'Nie. Vyber frekvenciu, ktorá zachová kvalitné prevedenie, regeneráciu a pravidelnosť. Viac kratších tréningov môže pomôcť, keď výkon ku koncu dlhého tréningu prudko klesá.' },
    { question: 'Je objemová záťaž to isté ako kvalita tréningu?', answer: 'Nie. Násobí záťaž opakovaniami, ale nezachytí rozsah pohybu, techniku, blízkosť zlyhania ani to, ktorý sval vykonal prácu.' },
    { question: 'Čo zapisovať pri porovnávaní rozvrhov?', answer: 'Cvik, záťaž, dokončené opakovania, prestávku a blízkosť zlyhania. Rozhoduj podľa trendu niekoľkých týždňov pri stabilných podmienkach.' },
  ],
  ctaPath: '/', ctaLabel: 'Zapisovať tréning v LIFTAG', secondaryPath: '/journal', secondaryLabel: 'Čítať ďalší výskum',
} satisfies typeof en
