import type { JournalArticle } from './types'

const pubmed = 'https://pubmed.ncbi.nlm.nih.gov/42709978/'
const doi = 'https://doi.org/10.1519/JSC.0000000000005665'

export const en = {
  slug: 'weekly-set-distribution',
  path: '/journal/weekly-set-distribution',
  titleHtml: 'One long leg day or <span class="lime">three short ones?</span>',
  titleText: 'One long leg day or three short ones?',
  description: 'How to decide whether your weekly sets belong in one long session or several shorter workouts, using your own training log.',
  seoTitle: 'Weekly Set Distribution: 1 vs 3 Training Days | LIFTAG',
  datePublished: '2026-10-07',
  category: 'RESEARCH',
  dateUpdated: '2026-10',
  citations: [pubmed, doi],
  body: `<section><h2>The short answer</h2><p>Jader Calzavara and Renato Barroso followed 18 trained men for six weeks. Each man did three weekly sets per exercise, either together on one day or spread over three days. Spreading the work raised the total weight lifted, but neither strength nor quadriceps thickness was significantly better in one group. That does not prove the schedules are equal; the study was small and short.</p></section>
<section><h2>Why the total went up</h2><p>“Volume load” sounds technical, but it is just weight multiplied by repetitions. If you squat 100 kg for 10 reps, that set adds 1,000 kg to the total.</p><p>Now imagine three squat sets on Monday: 10 reps, then 8, then 6 as fatigue builds. The log shows 24 reps. Put one set on Monday, Wednesday and Friday, and you might manage 10 each time because you begin fresh. The plan still says three sets at 100 kg, yet the completed work is different.</p><p>That total is useful, but it is not a score for muscle growth. It says nothing about depth, technique, effort or which muscles carried the rep. It makes most sense when you compare the same exercise, done in the same way, by the same person.</p></section>
<section><h2>Read the sets, not only the plan</h2><p>A weekly total can hide what happened inside the session. Record the weight and reps for every set, along with the rest time and how hard the set felt. Then the drop from set one to set three is visible instead of disappearing inside “three sets completed.”</p><p>The pattern matters more than one bad workout. A short night, a rushed warm-up or a busy gym can change a single session. Several weeks of the same drop-off tell a clearer story. They show whether the later sets are consistently weaker and whether a different schedule changes that.</p><p>Keep the comparison understandable. If the schedule changes, leave the exercises and their setup alone where possible. Otherwise a better result may come from the new exercise, the new load or the new timetable, and the log cannot separate them.</p></section>
<section><h2>The same weekly count can tell two stories</h2><p>A plan may show nine sets for the legs in both weeks. In week one, all nine happen on Monday and the final exercises lose reps. In week two, the sets are divided across three visits and the reps stay steadier. The set count is identical, while the sessions feel and unfold differently.</p><p>This is why the individual entries matter. They preserve where the work sat, what happened as fatigue built and whether the planned sets were actually completed. The weekly total becomes a summary of the log instead of a substitute for it.</p></section>
<section><h2>The timetable has a cost too</h2><p>Three short visits and one long visit take time in different ways. Another gym day means more travel, changing, warming up and another date to keep. The reward is a shorter session and less fatigue before each set. A row marked “three weekly sets” captures none of that.</p><p>Write down the actual problem. “I lose four reps by my third squat set” is clear. So is “leg day now takes 95 minutes.” Those notes give the numbers a purpose. If spreading the sets fixes one problem but creates missed sessions elsewhere, the full log will show that as well.</p><p>Exercises also carry different costs. One hard squat set can affect the rest of a workout more than one leg-extension set. Two exercises may both count as a set for the quadriceps without taking the same amount out of you.</p></section>
<section><h2>What the study changes</h2><p>It gives a good reason to distinguish planned work from completed work. The same load and number of sets on paper can produce different repetition totals depending on where those sets sit in the week.</p><p>It does not turn three sets into three required gym visits. A single leg day may fit someone’s week better. Several shorter sessions may suit someone whose later sets repeatedly fall apart. The study leaves that choice open, and its lack of a significant group difference is not proof that the choices produce identical results.</p><p>Source: Jader Calzavara and Renato Barroso, “Effects of Weekly Set Distribution on Volume Load, Lower-Body Strength, and Quadriceps Muscle Thickness in Trained Men,” <em>Journal of Strength and Conditioning Research</em>, 2026. Read the <a href="${pubmed}">PubMed record</a> or the <a href="${doi}">paper page</a>. Links checked 7 October 2026.</p></section>`,
  faqs: [
    { question: 'Is training a muscle three times per week always better than once?', answer: 'No. Choose a frequency that preserves good execution, recovery and consistency. Several shorter sessions can help when performance collapses late in a long workout.' },
    { question: 'Is volume load the same as training quality?', answer: 'No. It records load multiplied by repetitions, but cannot capture how far you moved, your technique, how many good reps you felt you had left or which muscle did the work.' },
    { question: 'What should I log when comparing schedules?', answer: 'Record the exercise, weight, completed reps, rest time and how many good reps you felt you had left. Compare several weeks under stable conditions rather than judging one workout.' },
  ],
  ctaPath: '/', ctaLabel: 'Track your training with LIFTAG', secondaryPath: '/journal', secondaryLabel: 'Read more research',
} satisfies JournalArticle

export const sk = {
  slug: 'weekly-set-distribution',
  path: '/journal/weekly-set-distribution',
  titleHtml: 'Jeden dlhý tréning nôh alebo <span class="lime">tri krátke?</span>',
  titleText: 'Jeden dlhý tréning nôh alebo tri krátke?',
  description: 'Ako podľa vlastného tréningového denníka rozhodnúť, či týždenné série patria do jedného dlhého alebo viacerých kratších tréningov.',
  seoTitle: 'Rozdelenie sérií: 1 alebo 3 tréningové dni | LIFTAG',
  datePublished: '2026-10-07', category: 'VÝSKUM', dateUpdated: '2026-10', citations: [pubmed, doi],
  body: `<section><h2>Krátka odpoveď</h2><p>Jader Calzavara a Renato Barroso sledovali 18 trénovaných mužov počas šiestich týždňov. Každý robil tri série na cvik týždenne, buď naraz, alebo v troch dňoch. Rozdelenie zvýšilo celkovú zdvihnutú váhu, no sila ani hrúbka kvadricepsu neboli významne lepšie v jednej skupine. To nedokazuje rovnaký účinok; štúdia bola malá a krátka.</p></section>
<section><h2>Prečo celkový objem stúpol</h2><p>„Objemová záťaž“ znie odborne, ale znamená iba váhu vynásobenú opakovaniami. Ak spravíš drep so 100 kg desaťkrát, séria pridá do súčtu 1 000 kg.</p><p>Predstav si tri série drepu v pondelok: 10, potom 8 a napokon 6 opakovaní, keď sa nazbiera únava. Denník ukáže 24 opakovaní. Ak dáš po jednej sérii v pondelok, stredu a piatok, možno zakaždým zvládneš 10, pretože začínaš oddýchnutý. Plán stále hovorí tri série so 100 kg, ale vykonaná práca je iná.</p><p>Tento súčet je užitočný, no nie je skóre rastu svalov. Nevie nič o hĺbke, technike, úsilí ani o tom, ktoré svaly prevzali prácu. Najväčší zmysel má pri porovnaní rovnakého cviku, rovnakého prevedenia a toho istého človeka.</p></section>
<section><h2>Čítaj jednotlivé série, nie iba plán</h2><p>Týždenný súčet môže skryť priebeh tréningu. Zapíš váhu a opakovania každej série, čas prestávky aj pocitovú náročnosť. Pokles od prvej po tretiu sériu potom uvidíš namiesto toho, aby zmizol za poznámkou „tri série hotové“.</p><p>Dôležitejší je opakovaný vzorec než jeden zlý tréning. Krátky spánok, uponáhľaná rozcvička alebo plná posilňovňa môžu zmeniť jediný deň. Niekoľko týždňov s rovnakým poklesom už rozpráva jasnejší príbeh. Ukáže, či sú neskoršie série pravidelne slabšie a či ich iné rozloženie niečo zmení.</p><p>Porovnanie musí zostať zrozumiteľné. Ak meníš rozvrh, nechaj cviky a ich prevedenie podľa možnosti rovnaké. Inak môže lepší výsledok spôsobiť nový cvik, nová váha alebo nový kalendár a denník ich od seba neoddelí.</p></section>
<section><h2>Rovnaký týždenný počet môže rozprávať dva príbehy</h2><p>Plán môže v oboch týždňoch ukazovať deväť sérií na nohy. V prvom spravíš všetkých deväť v pondelok a pri posledných cvikoch strácaš opakovania. V druhom ich rozdelíš do troch návštev a výkon zostane vyrovnanejší. Počet sérií je rovnaký, ale tréningy prebiehajú a pôsobia inak.</p><p>Preto záleží na jednotlivých zápisoch. Uchovajú, kde sa práca nachádzala, čo sa dialo s rastúcou únavou a či boli plánované série naozaj dokončené. Týždenný súčet je potom zhrnutím denníka, nie jeho náhradou.</p></section>
<section><h2>Aj rozvrh niečo stojí</h2><p>Tri krátke návštevy a jedna dlhá spotrebujú čas inak. Ďalší deň v posilňovni znamená ďalšiu cestu, prezliekanie, rozcvičku a termín, ktorý môžeš vynechať. Odmenou je kratší tréning a menej únavy pred každou sériou. Riadok „tri série týždenne“ nič z toho nezachytí.</p><p>Pomenuj skutočný problém. „V tretej sérii drepu strácam štyri opakovania“ je jasné. Rovnako aj „tréning nôh už trvá 95 minút“. Také poznámky dávajú číslam význam. Ak rozdelenie sérií vyrieši jeden problém, ale spôsobí vynechané tréningy inde, celý denník ukáže aj to.</p><p>Aj cviky majú rozdielnu cenu. Jedna náročná séria drepu môže ovplyvniť zvyšok tréningu viac než séria predkopávania. Obe môžeš počítať ako jednu sériu na kvadriceps, no nevezmú ti rovnaké množstvo energie.</p></section>
<section><h2>Čo z toho vyplýva</h2><p>Štúdia pripomína, že naplánovaná a vykonaná práca nie sú to isté. Rovnaká váha a počet sérií na papieri môžu vytvoriť iný počet opakovaní podľa toho, kde ich v týždni umiestniš.</p><p>Nerobí však z troch sérií tri povinné návštevy posilňovne. Jednému človeku môže lepšie sedieť jeden deň nôh. Inému viac kratších tréningov, ak sa mu neskoršie série pravidelne rozpadajú. Výber zostáva otvorený a chýbajúci významný rozdiel medzi skupinami neznamená, že výsledky sú určite rovnaké.</p><p>Zdroj: Jader Calzavara a Renato Barroso, „Effects of Weekly Set Distribution on Volume Load, Lower-Body Strength, and Quadriceps Muscle Thickness in Trained Men“, <em>Journal of Strength and Conditioning Research</em>, 2026. Pozri si <a href="${pubmed}">záznam na PubMed</a> alebo <a href="${doi}">stránku článku</a>. Odkazy overené 7. októbra 2026.</p></section>`,
  faqs: [
    { question: 'Je tréning svalu trikrát týždenne vždy lepší než raz?', answer: 'Nie. Vyber frekvenciu, ktorá zachová kvalitné prevedenie, regeneráciu a pravidelnosť. Viac kratších tréningov môže pomôcť, keď výkon ku koncu dlhého tréningu prudko klesá.' },
    { question: 'Je objemová záťaž to isté ako kvalita tréningu?', answer: 'Nie. Násobí záťaž opakovaniami, ale nezachytí rozsah pohybu, techniku, koľko čistých opakovaní ti ešte zostávalo ani to, ktorý sval vykonal prácu.' },
    { question: 'Čo zapisovať pri porovnávaní rozvrhov?', answer: 'Cvik, váhu, dokončené opakovania, prestávku a koľko čistých opakovaní ti ešte zostávalo. Rozhoduj podľa trendu niekoľkých týždňov pri stabilných podmienkach.' },
  ],
  ctaPath: '/', ctaLabel: 'Zapisovať tréning v LIFTAG', secondaryPath: '/journal', secondaryLabel: 'Čítať ďalší výskum',
} satisfies typeof en
