import type { JournalArticle } from './types'

export const en = {
  slug: 'what-workout-logs-reveal',
  path: '/journal/what-workout-logs-reveal',
  titleHtml: 'What workout logs reveal about <span class="lime">real progress.</span>',
  titleText: 'What workout logs reveal about real progress.',
  description:
    'GymStreak analysed millions of logged sets and hundreds of thousands of consecutive lift sessions. The useful finding is not a magic programme: most progress is repetitive, uneven and easy to misread.',
  seoTitle: 'What 27.5M Workout Sets Reveal About Progress | LIFTAG',
  datePublished: '2026-10-07',
  category: 'RESEARCH',
  dateUpdated: '2026-10',
  citations: [
    'https://www.gymstreak.com/research/how-lifters-train',
    'https://www.gymstreak.com/research/how-lifters-progress',
  ],
  body: `<section><h2>Two reports, one useful reality check</h2><p>GymStreak published two analyses of its own workout logs in September and October 2026. The first describes how its users train. The second follows streaks, repeat sessions and estimated personal records. Together they put numbers behind something a good training diary makes obvious: progress rarely looks like a heavier number every Monday.</p><p>The scale is unusual. The training report covers 27.5 million logged sets from 149,299 GymStreak users between December 2019 and September 2026. The progression report compares 723,068 pairs of sessions on the same lift, drawn from 22,819 users. GymStreak is the named corporate author of both reports. These are company product-data studies, not peer-reviewed papers, but the methods and aggregate download tables are public.</p></section>
<section><h2>Most logged training is deliberately ordinary</h2><p>The typical weighted set in the data was 10 reps. Three working sets was the most common exercise entry, with four sets close behind. Only a small share of logged sets sat in the heavy one-to-five-rep range, except on the bench press, squat and deadlift.</p><p>That does not prove that three sets of ten is optimal. It shows how strongly programmes, equipment and habit pull people towards familiar round numbers. It also explains why a log needs more than a single headline set. If most sessions live in the same rep neighbourhood, the useful signal is the gradual change in load, reps, execution and total work.</p><p>The session data makes that pattern clearer. When GymStreak compared the top working weight with the previous session of the same lift, the load stayed the same just over half the time. It rose in about a third of comparisons and fell in the rest. Holding the weight was not automatically a stalled session: some users added repetitions, and the study did not measure technique, range of motion or effort.</p></section>
<section><h2>A repeated weight can still be progress</h2><p>A tracker can tempt you to treat every unchanged number as failure. That is the wrong resolution. If 80 kg moves for eight clean reps after last week\'s seven, the weight stayed still while performance improved. If the same eight reps move with a pause and a lower RPE, the log needs enough context to preserve that change.</p><p>The size of the reported weight jumps is another warning. When users did increase the load, the typical increase was larger than the small percentage steps usually recommended for controlled progression. Dumbbells and machine stacks force chunky jumps. A two-kilogram jump on a lateral raise is a very different demand from the same jump on a deadlift. Double progression—add reps first, then take the smallest available load step—is often the honest answer.</p><p>This lines up with our practical guide to <a href="/journal/progressive-overload">progressive overload</a>. Load is one lever. Reps, sets and repeatable technique are others. A log should help you choose one, rather than pressure you to manufacture a new record.</p></section>
<section><h2>Personal records become rare because the baseline gets real</h2><p>GymStreak estimated a one-rep max from sets of ten reps or fewer and asked whether each session beat all earlier sessions on that lift. About half of second sessions produced a new estimated best. By the tenth session it was below one in five, and after dozens of sessions it was uncommon.</p><p>That curve is not evidence that training stops working. Early records are cheap because the history is almost empty, technique is improving and the first logged set may be conservative. Later records have to beat a stronger, more stable baseline. This is why a mature training log can look quieter while the lifter is doing better work.</p><p>The one-year comparisons need even more restraint. They include only people who were still logging the same lift at each checkpoint. People who stopped, became injured or switched exercises disappear from the analysis. The authors explicitly flag this survivor bias. Estimated maxes also depend on accurate self-entered weights and the Epley formula; they are trends, not tested competition lifts.</p></section>
<section><h2>What the reports cannot tell us</h2><ul><li>The sample is self-selected: these are GymStreak users who logged workouts, not all gym members.</li><li>A missing log is not proof of a missed workout, and the reports cannot observe unrecorded training.</li><li>About a third of the training-report sets came from 2022, so the all-time picture is not evenly distributed across years.</li><li>The company is analysing its own product data. The transparent method helps, but there is no independent validation or peer review.</li><li>Top weight and estimated 1RM leave out sleep, pain, technique, proximity to failure and programme intent.</li></ul><p>The right conclusion is modest. Training progress is a slow signal inside repetitive sessions. Record enough detail to compare like with like, then judge a block over weeks rather than demanding a badge from every workout.</p></section>
<section><h2>Sources and reuse</h2><ul><li>GymStreak. “How lifters actually train.” Published 30 September 2026: <a href="https://www.gymstreak.com/research/how-lifters-train">gymstreak.com</a></li><li>GymStreak. “How lifters progress.” Published 5 October 2026: <a href="https://www.gymstreak.com/research/how-lifters-progress">gymstreak.com</a></li></ul><p>Both pages were checked 7 October 2026. GymStreak licenses the downloadable aggregate summary tables under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> and asks users to credit and link the report. This article is an original analysis; it does not reproduce the reports\' prose, graphics or tables.</p></section>`,
  faqs: [
    { question: 'Should the weight increase every workout?', answer: 'No. In GymStreak’s session-pair data, the top weight stayed the same more often than it rose. You can progress through more reps, better technique or more controlled effort before increasing the load.' },
    { question: 'Why do personal records become less frequent?', answer: 'Your early history is easy to beat. As your baseline becomes stronger and more stable, a real record needs a larger improvement. Fewer PR notifications do not mean that training stopped working.' },
    { question: 'Does this study represent every lifter?', answer: 'No. It describes self-selected GymStreak users who logged workouts. Missing logs, people who changed exercises and people who stopped using the app limit what the results can say.' },
    { question: 'Are the GymStreak reports peer reviewed?', answer: 'No. They are transparent industry product-data reports with published methods and downloadable aggregate tables, but they are not peer-reviewed academic studies.' },
  ],
  ctaPath: '/',
  ctaLabel: 'Get LIFTAG free',
  secondaryPath: '/journal/progressive-overload',
  secondaryLabel: 'Read about progressive overload',
} satisfies JournalArticle

export const sk = {
  slug: 'what-workout-logs-reveal',
  path: '/journal/what-workout-logs-reveal',
  titleHtml: 'Čo tréningové záznamy ukazujú o <span class="lime">skutočnom progrese.</span>',
  titleText: 'Čo tréningové záznamy ukazujú o skutočnom progrese.',
  description:
    'GymStreak analyzoval milióny zapísaných sérií a státisíce po sebe idúcich tréningov cviku. Výsledkom nie je zázračný program: skutočný progres sa opakuje, kolíše a ľahko sa číta nesprávne.',
  seoTitle: 'Čo 27,5 milióna sérií ukazuje o progrese | LIFTAG',
  datePublished: '2026-10-07',
  category: 'VÝSKUM',
  dateUpdated: '2026-10',
  citations: [
    'https://www.gymstreak.com/research/how-lifters-train',
    'https://www.gymstreak.com/research/how-lifters-progress',
  ],
  body: `<section><h2>Dve správy a jedno užitočné vytriezvenie</h2><p>GymStreak v septembri a októbri 2026 zverejnil dve analýzy vlastných tréningových záznamov. Prvá opisuje, ako jeho používatelia trénujú. Druhá sleduje série pravidelných týždňov, opakované tréningy cvikov a odhadované osobné rekordy. Spoločne dávajú čísla tomu, čo dobrý denník ukáže aj bez veľkej štúdie: progres málokedy znamená vyššiu váhu každý pondelok.</p><p>Rozsah dát je neobvyklý. Prvá správa zahŕňa 27,5 milióna zapísaných sérií od 149 299 používateľov GymStreaku od decembra 2019 do septembra 2026. Druhá porovnáva 723 068 dvojíc tréningov rovnakého cviku od 22 819 používateľov. Ako autor oboch správ je uvedená spoločnosť GymStreak. Ide o firemné analýzy produktových dát, nie o recenzované vedecké práce, no metódy aj súhrnné tabuľky na stiahnutie sú verejné.</p></section>
<section><h2>Väčšina tréningu je zámerne obyčajná</h2><p>Typická pracovná séria so záťažou mala v dátach desať opakovaní. Najčastejšie boli tri pracovné série na cvik a tesne za nimi štyri. Iba malá časť sérií patrila do ťažkého rozsahu jedného až piatich opakovaní; výnimkou boli bench press, drep a mŕtvy ťah.</p><p>To nedokazuje, že tri série po desať sú optimálne. Ukazuje to silu programov, dostupného vybavenia a zvyku, ktoré ľudí vedú k známym okrúhlym číslam. Zároveň vysvetľuje, prečo nestačí zapisovať jedinú hlavnú sériu. Keď sa väčšina tréningov pohybuje v rovnakom rozsahu, signálom je pomalá zmena záťaže, opakovaní, prevedenia a celkovej práce.</p><p>Porovnanie po sebe idúcich tréningov to ukazuje ešte jasnejšie. Keď GymStreak porovnal najvyššiu pracovnú váhu s predchádzajúcim tréningom toho istého cviku, vo viac než polovici prípadov zostala rovnaká. Približne v tretine stúpla a vo zvyšku klesla. Rovnaká váha však automaticky neznamená stagnáciu: niektorí pridali opakovania a analýza nemerala techniku, rozsah pohybu ani náročnosť.</p></section>
<section><h2>Rovnaká váha môže byť progres</h2><p>Tracker môže zvádzať k tomu, aby si každé nezmenené číslo považoval za neúspech. Takto sa však na tréning pozeráš príliš zblízka. Ak po minulotýždňových siedmich čistých opakovaniach zvládneš s 80 kg osem, váha sa nezmenila, ale výkon áno. Ak rovnakých osem opakovaní zvládneš s pauzou a nižším RPE, denník potrebuje dosť kontextu, aby túto zmenu zachoval.</p><p>Varovaním je aj veľkosť skokov. Keď používatelia záťaž zvýšili, typický skok bol väčší než malé percentuálne kroky odporúčané na kontrolovaný postup. Jednoručky a zásobníky strojov nútia robiť veľké skoky. Dve kilá navyše pri upažovaní znamenajú úplne inú požiadavku než dve kilá pri mŕtvom ťahu. Dvojitá progresia—najprv opakovania, potom najmenší dostupný krok záťaže—je často poctivejším riešením.</p><p>Zodpovedá to nášmu praktickému návodu na <a href="/journal/progressive-overload">progresívne preťaženie</a>. Záťaž je iba jedna páka. Ďalšími sú opakovania, série a opakovateľná technika. Denník ti má pomôcť vybrať jednu z nich, nie ťa tlačiť do vymysleného rekordu.</p></section>
<section><h2>Rekordy rednú, pretože základ je čoraz skutočnejší</h2><p>GymStreak odhadol maximum na jedno opakovanie zo sérií do desiatich opakovaní a sledoval, či tréning prekonal všetky skoršie tréningy daného cviku. Približne polovica druhých tréningov priniesla nový odhadovaný rekord. Pri desiatom tréningu to bolo menej než raz z piatich a po desiatkach tréningov už išlo o zriedkavú udalosť.</p><p>Krivka neznamená, že tréning prestal fungovať. Prvé rekordy sú lacné, pretože história je takmer prázdna, technika sa zlepšuje a prvý zápis mohol byť opatrný. Neskorší rekord musí prekonať silnejší a stabilnejší základ. Preto môže vyzretý tréningový denník pôsobiť pokojnejšie aj vtedy, keď cvičenec odvádza lepšiu prácu.</p><p>Ročné porovnania si žiadajú ešte väčšiu opatrnosť. Zahŕňajú iba ľudí, ktorí pri danom cviku stále zapisovali tréning v každom kontrolnom bode. Ľudia, ktorí prestali, zranili sa alebo cvik vymenili, z analýzy vypadli. Autori priamo upozorňujú na toto skreslenie preživších. Odhad maxima navyše závisí od správne zapísaných váh a Epleyho vzorca; ukazuje trend, nie odskúšaný súťažný výkon.</p></section>
<section><h2>Čo z týchto správ nezistíme</h2><ul><li>Vzorka je samovýberová: ide o používateľov GymStreaku, ktorí si tréning zapisovali, nie o všetkých návštevníkov fitka.</li><li>Chýbajúci zápis nedokazuje vynechaný tréning a analýza nevidí nezapísané cvičenie.</li><li>Približne tretina sérií v prvej správe pochádza z roku 2022, takže roky nemajú rovnakú váhu.</li><li>Firma analyzuje vlastné produktové dáta. Verejná metodika pomáha, no chýba nezávislé overenie a odborné recenzné konanie.</li><li>Najvyššia váha a odhad 1RM nezachytávajú spánok, bolesť, techniku, rezervu opakovaní ani zámer programu.</li></ul><p>Záver preto zostáva skromný. Tréningový progres je pomalý signál ukrytý v opakujúcich sa tréningoch. Zapisuj dosť detailov na porovnanie rovnakých podmienok a blok posudzuj po týždňoch, nie podľa odznaku po každom tréningu.</p></section>
<section><h2>Zdroje a použitie dát</h2><ul><li>GymStreak. „How lifters actually train.“ Zverejnené 30. septembra 2026: <a href="https://www.gymstreak.com/research/how-lifters-train">gymstreak.com</a></li><li>GymStreak. „How lifters progress.“ Zverejnené 5. októbra 2026: <a href="https://www.gymstreak.com/research/how-lifters-progress">gymstreak.com</a></li></ul><p>Obe stránky sme overili 7. októbra 2026. GymStreak poskytuje súhrnné tabuľky na stiahnutie pod licenciou <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> a žiada uviesť zdroj a odkaz. Tento článok je pôvodná analýza; nepreberá text, grafiku ani tabuľky zo správ.</p></section>`,
  faqs: [
    { question: 'Mala by sa váha zvýšiť pri každom tréningu?', answer: 'Nie. V dátach GymStreaku zostala najvyššia váha rovnaká častejšie, než stúpla. Napredovať môžeš ďalším opakovaním, lepšou technikou alebo kontrolovanejšou náročnosťou pred zvýšením záťaže.' },
    { question: 'Prečo sú osobné rekordy časom zriedkavejšie?', answer: 'Prvú krátku históriu prekonáš ľahko. Keď je základ silnejší a stabilnejší, skutočný rekord si vyžaduje väčšie zlepšenie. Menej upozornení na PR neznamená, že tréning prestal fungovať.' },
    { question: 'Predstavuje analýza všetkých cvičencov?', answer: 'Nie. Opisuje používateľov GymStreaku, ktorí si tréning zapisovali. Chýbajúce záznamy, zmenené cviky a odchody z aplikácie obmedzujú závery.' },
    { question: 'Prešli správy GymStreaku odbornou recenziou?', answer: 'Nie. Ide o transparentné firemné analýzy produktových dát so zverejnenou metodikou a súhrnnými tabuľkami, nie o recenzované vedecké štúdie.' },
  ],
  ctaPath: '/',
  ctaLabel: 'Stiahnuť LIFTAG zadarmo',
  secondaryPath: '/journal/progressive-overload',
  secondaryLabel: 'Prečítať o progresívnom preťažení',
} satisfies typeof en
