import type { JournalArticle } from './types'

export const en = {
  slug: 'what-workout-logs-reveal',
  path: '/journal/what-workout-logs-reveal',
  titleHtml: 'What workout logs reveal about <span class="lime">real progress.</span>',
  titleText: 'What workout logs reveal about real progress.',
  description:
    'GymStreak studied 27.5 million logged sets and more than 700,000 pairs of exercise sessions. The data shows why progress often happens without adding weight.',
  seoTitle: 'What 27.5M Workout Sets Reveal About Progress | LIFTAG',
  datePublished: '2026-10-07',
  category: 'RESEARCH',
  dateUpdated: '2026-10',
  citations: [
    'https://www.gymstreak.com/research/how-lifters-train',
    'https://www.gymstreak.com/research/how-lifters-progress',
  ],
  body: `<section><h2>What the reports found</h2><p>Adding weight is only one sign of progress. Two reports from GymStreak show that lifters often repeat the same working weight, add a rep or simply build weeks of steady training before setting another record.</p><p>GymStreak published the reports in September and October 2026 using data from its own app. The first covers 27.5 million logged sets from 149,299 users between December 2019 and September 2026. The second compares 723,068 pairs of sessions on the same exercise from 22,819 users. GymStreak is the named corporate author. These are company analyses rather than peer-reviewed research, although the methods and downloadable summary tables are public.</p></section>
<section><h2>What a usual logged workout looked like</h2><p>The typical weighted set had 10 reps. Three working sets was the most common entry for an exercise, followed closely by four. Sets of one to five reps made up only a small part of the data, apart from bench press, squat and deadlift.</p><p>These figures describe what users logged; they do not prove that three sets of ten is the best way to train. Programmes, available equipment and familiar round numbers all shape a workout. They also show why one impressive set tells only part of the story. When sessions use similar rep ranges, changes in weight, reps, technique and total work become easier to see over several weeks.</p><p>GymStreak also compared the highest working weight in one session with the previous session for the same exercise. The weight stayed the same just over half the time. It increased in about a third of comparisons and decreased in the rest. An unchanged weight did not always mean an unchanged performance: some users did more reps, while the data did not capture technique, range of motion or effort.</p></section>
<section><h2>The same weight can still show improvement</h2><p>Suppose you lift 80 kg for seven clean reps this week and eight next week. The weight has not moved, but your result has. The same eight reps may also improve if they are more controlled or feel easier. RPE, or rating of perceived exertion, is one way to record that effort.</p><p>The reported increases in weight were often larger than the small percentage steps commonly used for gradual progression. Available equipment can explain some of this. A dumbbell rack or machine stack may leave no small step to take. Adding 2 kg to a lateral raise is also a much bigger relative change than adding 2 kg to a deadlift.</p><p>One practical option is to add reps before moving to the next available weight. This is often called double progression. Our guide to <a href="/journal/progressive-overload">progressive overload</a> also covers sets and consistent technique. A useful log lets you see which part changed.</p></section>
<section><h2>Why personal records become less common</h2><p>GymStreak estimated a one-rep maximum from sets of up to 10 reps. It then checked whether each session beat every earlier estimate for that exercise. About half of second sessions produced a new estimated best. By the tenth session, fewer than one in five did. After dozens of sessions, a new best was uncommon.</p><p>This pattern makes sense. The second entry only has to beat the first. Early improvements in technique can also move the number quickly. Later, a new record must beat a longer history and a stronger starting point. Fewer record notifications therefore do not show that training has stopped working.</p><p>The one-year results need extra care. They include only people who were still logging the same exercise at each checkpoint. Anyone who stopped logging, became injured or changed exercises dropped out of that comparison. The reports call out this selection problem, known as survivor bias. The estimates also rely on weights entered by users and the Epley formula. They are useful for following a trend, but they are not tested one-rep maximums.</p></section>
<section><h2>Limits of the data</h2><ul><li>The users chose GymStreak and chose to log their workouts, so they do not represent every lifter.</li><li>A missing entry does not prove that somebody missed a workout. Training outside the app is invisible.</li><li>About one third of the sets in the training report came from 2022, so each year does not contribute equally.</li><li>GymStreak analysed data from its own product. The public method is helpful, but the work has not been independently validated or peer reviewed.</li><li>Highest weight and estimated 1RM do not capture sleep, pain, technique, closeness to failure or the aim of the programme.</li></ul><p>Read the results as a picture of logged training, not a rule for every athlete. Compare similar sessions over several weeks and keep enough detail to understand why a number changed.</p></section>
<section><h2>Sources and reuse</h2><ul><li>GymStreak. “How lifters actually train.” Published 30 September 2026: <a href="https://www.gymstreak.com/research/how-lifters-train">gymstreak.com</a></li><li>GymStreak. “How lifters progress.” Published 5 October 2026: <a href="https://www.gymstreak.com/research/how-lifters-progress">gymstreak.com</a></li></ul><p>Both pages were checked 7 October 2026. GymStreak licenses the downloadable aggregate summary tables under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> and asks users to credit and link the report. This article is an original analysis; it does not reproduce the reports\' prose, graphics or tables.</p></section>`,
  faqs: [
    { question: 'Should the weight increase every workout?', answer: 'No. In GymStreak’s data, the highest working weight stayed the same more often than it increased. More reps at the same weight, cleaner technique or an easier-feeling set can also show improvement.' },
    { question: 'Why do personal records become less frequent?', answer: 'Your second session only has to beat your first. Later sessions must beat many previous attempts and a higher previous best, so new records naturally become less common. Fewer record notifications do not mean that training stopped working.' },
    { question: 'Does this study represent every lifter?', answer: 'No. It describes people who chose GymStreak and recorded workouts in it. The reports cannot see unrecorded training, and later comparisons leave out people who stopped logging or changed exercises.' },
    { question: 'Are the GymStreak reports peer reviewed?', answer: 'No. GymStreak published its methods and summary tables, but independent academic reviewers did not assess the reports before publication.' },
  ],
  ctaPath: '/',
  ctaLabel: 'Get LIFTAG free',
  secondaryPath: '/journal/progressive-overload',
  secondaryLabel: 'Read about progressive overload',
} satisfies JournalArticle

export const sk = {
  slug: 'what-workout-logs-reveal',
  path: '/journal/what-workout-logs-reveal',
  titleHtml: 'Čo tréningové záznamy ukazujú o <span class="lime">skutočnom progrese.</span>',
  titleText: 'Čo tréningové záznamy ukazujú o skutočnom progrese.',
  description:
    'GymStreak preskúmal 27,5 milióna sérií a viac než 700 000 dvojíc tréningov rovnakého cviku. Dáta ukazujú, prečo možno napredovať aj bez pridania váhy.',
  seoTitle: 'Čo 27,5 milióna sérií ukazuje o progrese | LIFTAG',
  datePublished: '2026-10-07',
  category: 'VÝSKUM',
  dateUpdated: '2026-10',
  citations: [
    'https://www.gymstreak.com/research/how-lifters-train',
    'https://www.gymstreak.com/research/how-lifters-progress',
  ],
  body: `<section><h2>Čo správy zistili</h2><p>Vyššia váha je iba jedným znakom progresu. Dve správy GymStreaku ukazujú, že cvičenci často zopakujú rovnakú pracovnú váhu, pridajú opakovanie alebo niekoľko týždňov pravidelne trénujú skôr, než vytvoria ďalší rekord.</p><p>GymStreak zverejnil správy v septembri a októbri 2026 na základe dát z vlastnej aplikácie. Prvá zahŕňa 27,5 milióna sérií od 149 299 používateľov medzi decembrom 2019 a septembrom 2026. Druhá porovnáva 723 068 dvojíc tréningov rovnakého cviku od 22 819 používateľov. Ako autor je uvedená spoločnosť GymStreak. Ide o firemné analýzy, nie o recenzovaný výskum, hoci metodika aj súhrnné tabuľky sú verejné.</p></section>
<section><h2>Ako vyzeral bežný zapísaný tréning</h2><p>Typická séria so záťažou mala 10 opakovaní. Najčastejším zápisom pri cviku boli tri pracovné série, tesne za nimi štyri. Série s jedným až piatimi opakovaniami tvorili iba malú časť dát. Výnimkou boli bench press, drep a mŕtvy ťah.</p><p>Tieto čísla opisujú zápisy používateľov. Nedokazujú, že tri série po desať sú najlepší tréning. Výsledok ovplyvňuje program, dostupné vybavenie aj obľuba okrúhlych čísel. Zároveň ukazuje, prečo jedna pôsobivá séria nehovorí celý príbeh. Pri podobných počtoch opakovaní lepšie uvidíš zmenu váhy, techniky a celkového objemu až po niekoľkých týždňoch.</p><p>GymStreak porovnal aj najvyššiu pracovnú váhu s predchádzajúcim tréningom rovnakého cviku. Vo viac než polovici prípadov zostala rovnaká. Približne v tretine stúpla a vo zvyšku klesla. Niektorí používatelia pri rovnakej váhe pridali opakovania. Dáta navyše nemerali techniku, rozsah pohybu ani náročnosť.</p></section>
<section><h2>Aj rovnaká váha môže znamenať zlepšenie</h2><p>Predstav si, že tento týždeň zvládneš so 80 kg sedem čistých opakovaní a o týždeň osem. Váha sa nezmenila, výkon áno. Zlepšením môže byť aj kontrolovanejšie prevedenie alebo nižšie RPE pri rovnakých ôsmich opakovaniach. RPE je vlastné hodnotenie náročnosti série.</p><p>Keď používatelia váhu zvýšili, typický skok bol väčší než malé percentuálne kroky používané pri postupnom napredovaní. Čiastočne to môže vysvetliť vybavenie. Stojan s jednoručkami alebo zásobník stroja často neponúka menší krok. Dve kilá navyše pri upažovaní sú pritom oveľa väčšou relatívnou zmenou než dve kilá pri mŕtvom ťahu.</p><p>Praktickou možnosťou je najprv pridať opakovania a až potom prejsť na najbližšiu váhu. Tento postup sa nazýva dvojitá progresia. Náš návod na <a href="/journal/progressive-overload">progresívne preťaženie</a> vysvetľuje aj úlohu sérií a stabilnej techniky. Dobrý denník ukáže, čo presne sa zmenilo.</p></section>
<section><h2>Prečo sú osobné rekordy časom zriedkavejšie</h2><p>GymStreak odhadol maximum na jedno opakovanie zo sérií do 10 opakovaní. Potom sledoval, či každý ďalší tréning prekonal všetky skoršie odhady daného cviku. Približne polovica druhých tréningov priniesla nový odhadovaný rekord. Pri desiatom tréningu to bolo menej než raz z piatich. Po desiatkach tréningov bol nový rekord nezvyčajný.</p><p>Druhý zápis musí prekonať iba prvý. Na začiatku sa môže rýchlo zlepšovať aj technika. Neskôr rekord súťaží s dlhšou históriou a vyšším základom. Menej upozornení na rekord preto neznamená, že tréning prestal fungovať.</p><p>Ročné výsledky treba čítať zvlášť opatrne. Zahŕňajú iba ľudí, ktorí pri každej kontrole stále zapisovali rovnaký cvik. Z porovnania vypadli tí, ktorí prestali zapisovať, zranili sa alebo cvik zmenili. Správy tento výberový problém, nazývaný skreslenie preživších, priamo uvádzajú. Odhady tiež závisia od váh zadaných používateľmi a od Epleyho vzorca. Sledujú trend, nie skutočne odmerané maximum.</p></section>
<section><h2>Čo dáta nedokážu povedať</h2><ul><li>Používatelia si vybrali GymStreak aj samotné zapisovanie, preto nereprezentujú všetkých cvičencov.</li><li>Chýbajúci zápis nedokazuje vynechaný tréning. Cvičenie mimo aplikácie v dátach nevidno.</li><li>Približne tretina sérií v prvej správe pochádza z roku 2022, takže jednotlivé roky nemajú rovnakú váhu.</li><li>GymStreak analyzoval dáta vlastného produktu. Verejná metodika pomáha, ale analýzu nikto nezávisle neoveril a neprešla odborným recenzným konaním.</li><li>Najvyššia váha a odhad 1RM nezachytávajú spánok, bolesť, techniku, blízkosť zlyhania ani cieľ programu.</li></ul><p>Výsledky opisujú tréning zapísaný v jednej aplikácii, nie pravidlo pre každého. Porovnávaj podobné tréningy počas viacerých týždňov a zapisuj dosť detailov na pochopenie zmeny.</p></section>
<section><h2>Zdroje a použitie dát</h2><ul><li>GymStreak. „How lifters actually train.“ Zverejnené 30. septembra 2026: <a href="https://www.gymstreak.com/research/how-lifters-train">gymstreak.com</a></li><li>GymStreak. „How lifters progress.“ Zverejnené 5. októbra 2026: <a href="https://www.gymstreak.com/research/how-lifters-progress">gymstreak.com</a></li></ul><p>Obe stránky sme overili 7. októbra 2026. GymStreak poskytuje súhrnné tabuľky na stiahnutie pod licenciou <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> a žiada uviesť zdroj a odkaz. Tento článok je pôvodná analýza; nepreberá text, grafiku ani tabuľky zo správ.</p></section>`,
  faqs: [
    { question: 'Mala by sa váha zvýšiť pri každom tréningu?', answer: 'Nie. V dátach GymStreaku zostala najvyššia pracovná váha rovnaká častejšie, než stúpla. Zlepšenie môže ukázať aj viac opakovaní, čistejšia technika alebo ľahší pocit pri rovnakej sérii.' },
    { question: 'Prečo sú osobné rekordy časom zriedkavejšie?', answer: 'Druhý tréning musí prekonať iba prvý. Neskôr porovnávaš výsledok s mnohými pokusmi a s vyšším doterajším rekordom, preto nové rekordy prirodzene pribúdajú pomalšie. Menej upozornení na rekord neznamená, že tréning prestal fungovať.' },
    { question: 'Predstavuje analýza všetkých cvičencov?', answer: 'Nie. Opisuje ľudí, ktorí si vybrali GymStreak a zapisovali v ňom tréningy. Správy nevidia nezapísané cvičenie a z neskorších porovnaní vypadli ľudia, ktorí prestali zapisovať alebo zmenili cvik.' },
    { question: 'Prešli správy GymStreaku odbornou recenziou?', answer: 'Nie. GymStreak zverejnil metodiku aj súhrnné tabuľky, ale správy pred vydaním neposudzovali nezávislí vedeckí recenzenti.' },
  ],
  ctaPath: '/',
  ctaLabel: 'Stiahnuť LIFTAG zadarmo',
  secondaryPath: '/journal/progressive-overload',
  secondaryLabel: 'Prečítať o progresívnom preťažení',
} satisfies typeof en
