import type { JournalArticle } from './types'

export const en = {
  slug: 'why-workout-logging-habits-fade',
  path: '/journal/why-workout-logging-habits-fade',
  titleHtml: 'Why workout logging habits <span class="lime">fade.</span>',
  titleText: 'Why workout logging habits fade.',
  description:
    'A 2026 study followed Fitbod workout records for a year. Regular logging in the first month was linked with staying longer, but an empty log does not prove that training stopped.',
  seoTitle: 'Why Workout Logging Habits Fade: A 2026 Study | LIFTAG',
  datePublished: '2026-10-07',
  category: 'RESEARCH',
  dateUpdated: '2026-10',
  citations: [
    'https://www.frontiersin.org/journals/sports-and-active-living/articles/10.3389/fspor.2026.1855668/full',
    'https://doi.org/10.3389/fspor.2026.1855668',
  ],
  body: `<section><h2>What the study actually measured</h2><p>Workout logs often become less regular after the first few weeks. A large Fitbod study found that people who logged more active days in their first month tended to keep recording workouts for longer. It did not show that frequent early training caused the habit to last.</p><p>Federica Conti, Thiago Marzagão, Andrew J. Galpin and Brad J. Schoenfeld published the observational study in <em>Frontiers in Sports and Active Living</em> in August 2026. The full dataset contained 389,481 adults who described themselves as beginners, intermediate or advanced. The main analysis followed 100,709 beginners.</p><p>These beginners had already logged at least one workout in each week of their first 28 days. They also needed a full year of possible follow-up. This matters because the study leaves out people who tried the app and stopped during the first month.</p><p>Within this selected group, the estimated halfway point for dropout was 19 weeks. About one in ten still met the study’s rule at week 52. The rule required at least one recorded workout each week after the first month. Six empty weeks were allowed across the year; the seventh counted as dropout.</p></section>
<section><h2>Regular starts were linked with longer logging</h2><p>The researchers examined the first 28 days, including active days, workout length, strength, cardio and mobility work, available equipment and subscription status. The number of active days had the strongest link with a lower chance of later dropout. That link was strongest near the start and became weaker over time.</p><p>This is an association, not a training instruction. Someone who exercises regularly in month one may already have more time, confidence, support or motivation. Those differences could also help that person continue. The study cannot tell us that pushing every beginner into more sessions would produce the same result.</p><p>Using more kinds of equipment and recording a greater share of resistance exercise were also linked with staying longer. Among people who trained more often, longer recorded workouts were associated with a lower dropout rate, especially early in the year. The authors had to limit unusually long durations caused by running timers, duplicate entries and syncing problems. The result does not mean that beginners need long workouts.</p></section>
<section><h2>An empty log is not the same as no exercise</h2><p>The researchers used activity in the app as an indirect measure of exercise. The records included workouts created in Fitbod and sessions imported from Apple Health, Fitbit and Strava. If a week is empty, the person may have stopped training. They may also have changed apps, lost a watch sync or trained without recording it.</p><p>The careful wording is therefore “stopped logging.” The study cannot confirm that somebody “stopped exercising.” This limit applies to retention data from any workout app.</p><p>A saved workout has limits too. It confirms that a record exists, not that every listed rep happened exactly as entered. Time-stamped app data avoids some problems of asking people to remember old workouts, but typing mistakes and device errors remain.</p></section>
<section><h2>The first-month requirement changes the picture</h2><p>The selected beginners recorded activity on roughly half the days in their opening month. Most also bought a paid subscription during that time. They had already given the app a meaningful amount of attention before the follow-up started.</p><p>For that reason, the one-year figure is not the chance that any new lifter will keep exercising. It answers a narrower question: among Fitbod beginners who logged every week for their first 28 days, which early patterns were linked with continuing under the study’s seven-missed-week rule?</p><p>There is still a useful takeaway. Choose a first-month schedule that fits ordinary life and make the act of recording simple. After a missed session, continue with the next one instead of treating a broken streak as failure. These are practical ways to support a logging habit, though this study did not test them as interventions.</p></section>
<section><h2>Strengths and limits</h2><ul><li>The preregistered study followed a very large real-world group for 12 months.</li><li>It looked at when people dropped out and repeated the analysis with different assumptions, rather than relying on one end-of-year count.</li><li>It clearly defines who was included, what counted as dropout and how many empty weeks were allowed.</li><li>Because the study is observational, it cannot prove that workout frequency, duration or equipment variety caused people to stay.</li><li>Fitbod supplied the app data, and co-author Thiago Marzagão was employed by Fitbod. The paper discloses this conflict.</li><li>The dataset recorded sex only as male or female, and training experience was self-reported. Both choices limit what the results represent.</li></ul><p>The study supports a simple reading: early regularity can help identify people who will keep using a workout log. It does not tell us why each person stayed, and it cannot see exercise that was never recorded.</p></section>
<section><h2>Source</h2><p>Conti F, Marzagão T, Galpin AJ and Schoenfeld BJ. “Predictors of long-term resistance exercise adherence: evidence from a large cohort of mobile app users of various experience levels.” <em>Frontiers in Sports and Active Living</em>, published 10 August 2026. <a href="https://doi.org/10.3389/fspor.2026.1855668">doi:10.3389/fspor.2026.1855668</a>.</p><p>Source checked 7 October 2026. The peer-reviewed article is open access under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. This LIFTAG article paraphrases and critiques the study; it does not reproduce its figures or tables.</p></section>`,
  faqs: [
    { question: 'What did the Fitbod adherence study find?', answer: 'Among beginners who had already logged at least once a week during their first 28 days, more active days early on were most strongly linked with continued logging. About one in ten still met the study’s rule after one year. The result concerns app records and does not prove that others stopped exercising.' },
    { question: 'Does stopping workout logs mean someone stopped exercising?', answer: 'Not necessarily. A blank week may mean no exercise, but it may also mean a changed app, a failed import or a workout that was never recorded. The study could measure entries in Fitbod, not everything a person did outside it.' },
    { question: 'Did frequent early workouts cause people to stick with exercise?', answer: 'The study cannot show cause and effect. People who trained often in the first month may also have had more time, motivation, support or better health, which could help explain why they continued.' },
    { question: 'Was the study independent of Fitbod?', answer: 'Fitbod supplied the data with identifying details removed, and co-author Thiago Marzagão worked for Fitbod. The paper states this relationship. The other authors reported no business or financial conflict.' },
  ],
  ctaPath: '/',
  ctaLabel: 'Get LIFTAG free',
  secondaryPath: '/journal/how-to-track-workouts',
  secondaryLabel: 'How to track workouts',
} satisfies JournalArticle

export const sk = {
  slug: 'why-workout-logging-habits-fade',
  path: '/journal/why-workout-logging-habits-fade',
  titleHtml: 'Prečo návyk zapisovať si tréning <span class="lime">vyprchá.</span>',
  titleText: 'Prečo návyk zapisovať si tréning vyprchá.',
  description:
    'Štúdia z roku 2026 sledovala záznamy používateľov Fitbodu počas jedného roka. Pravidelné zapisovanie v prvom mesiaci súviselo s dlhším používaním, no prázdny denník nedokazuje koniec cvičenia.',
  seoTitle: 'Prečo návyk zapisovať tréning vyprchá: štúdia 2026 | LIFTAG',
  datePublished: '2026-10-07',
  category: 'VÝSKUM',
  dateUpdated: '2026-10',
  citations: [
    'https://www.frontiersin.org/journals/sports-and-active-living/articles/10.3389/fspor.2026.1855668/full',
    'https://doi.org/10.3389/fspor.2026.1855668',
  ],
  body: `<section><h2>Čo štúdia skutočne merala</h2><p>Tréningový denník býva po prvých týždňoch čoraz redší. Veľká štúdia Fitbodu zistila, že ľudia s väčším počtom aktívnych dní v prvom mesiaci mali sklon zapisovať dlhšie. Nedokázala však, že častejšie úvodné tréningy spôsobili trvácnejší návyk.</p><p>Federica Conti, Thiago Marzagão, Andrew J. Galpin a Brad J. Schoenfeld zverejnili observačnú štúdiu v auguste 2026 v časopise <em>Frontiers in Sports and Active Living</em>. Celý súbor zahŕňal 389 481 dospelých, ktorí sa označili za začiatočníkov, stredne pokročilých alebo pokročilých. Hlavná analýza sledovala 100 709 začiatočníkov.</p><p>Títo začiatočníci už počas prvých 28 dní zaznamenali aspoň jeden tréning každý týždeň. Zároveň museli mať k dispozícii celý rok možného sledovania. Štúdia teda nezahŕňa ľudí, ktorí aplikáciu vyskúšali a prestali používať ešte v prvom mesiaci.</p><p>Odhadovaný medián času do odpadnutia bol 19 týždňov. To znamená, že približne polovica tejto vybranej skupiny dovtedy splnila pravidlo pre koniec zapisovania. Približne jeden z desiatich spĺňal pravidlo štúdie aj v 52. týždni. Po prvom mesiaci sa vyžadoval aspoň jeden zaznamenaný tréning týždenne. Počas roka bolo povolených šesť prázdnych týždňov; siedmy sa počítal ako odpadnutie.</p></section>
<section><h2>Pravidelný začiatok súvisel s dlhším zapisovaním</h2><p>Výskumníci skúmali prvých 28 dní: aktívne dni, dĺžku tréningov, silové cvičenie, kardio a mobilitu, dostupné vybavenie aj predplatné. Počet aktívnych dní mal najsilnejšiu súvislosť s nižšou pravdepodobnosťou neskoršieho odpadnutia. Táto súvislosť bola najsilnejšia na začiatku a časom slabla.</p><p>Ide o súvislosť, nie tréningový návod. Človek, ktorý v prvom mesiaci cvičí pravidelne, môže mať viac času, sebadôvery, podpory alebo motivácie. Tie isté rozdiely mu môžu pomôcť pokračovať. Štúdia nedokáže povedať, že viac tréningov prinesie rovnaký výsledok každému začiatočníkovi.</p><p>S dlhším používaním súviselo aj viac druhov vybavenia a vyšší podiel silového cvičenia. U častejšie trénujúcich ľudí sa s nižším odpadnutím spájali dlhšie zaznamenané tréningy, najmä v úvode roka. Autori však museli obmedziť nezvyčajne dlhé trvania spôsobené bežiacimi časovačmi, duplicitami a chybami synchronizácie. Výsledok preto nehovorí, že začiatočníci potrebujú dlhé tréningy.</p></section>
<section><h2>Prázdny denník neznamená nulové cvičenie</h2><p>Autori použili aktivitu v aplikácii ako nepriamy ukazovateľ cvičenia. Záznamy zahŕňali tréningy vytvorené vo Fitbode aj aktivity importované z Apple Health, Fitbit a Strava. Prázdny týždeň môže znamenať koniec tréningu. Môže však znamenať aj inú aplikáciu, chybu synchronizácie hodiniek alebo cvičenie bez zápisu.</p><p>Presné tvrdenie preto znie „prestal zapisovať“. Štúdia nevie potvrdiť, že človek „prestal cvičiť“. Rovnaké obmedzenie platí pre údaje o udržaní používateľov v každej tréningovej aplikácii.</p><p>Aj uložený tréning má svoje hranice. Potvrdzuje existenciu záznamu, nie to, že každé opakovanie prebehlo presne podľa neho. Časové údaje z aplikácie odstraňujú niektoré chyby spomienok, no zostávajú preklepy a chyby zariadení.</p></section>
<section><h2>Podmienka prvého mesiaca mení význam výsledkov</h2><p>Vybraní začiatočníci zaznamenali aktivitu približne v polovici dní úvodného mesiaca. Väčšina si v tomto období kúpila predplatné. Už pred začiatkom ďalšieho sledovania teda venovali aplikácii dosť pozornosti a často aj peniaze.</p><p>Ročný výsledok preto nie je pravdepodobnosťou, že ľubovoľný nový cvičenec vydrží cvičiť. Odpovedá na užšiu otázku: ktoré úvodné vzorce u začiatočníkov Fitbodu, ktorí zapisovali každý týždeň prvých 28 dní, súviseli s pokračovaním podľa pravidla siedmich vynechaných týždňov?</p><p>Praktický záver je jednoduchý. Na prvý mesiac si vyber rozvrh, ktorý sa zmestí do bežného života, a uľahči si samotný zápis. Po vynechanom tréningu pokračuj ďalším namiesto toho, aby si prerušenú sériu považoval za neúspech. Štúdia však tieto postupy priamo netestovala.</p></section>
<section><h2>Silné stránky a obmedzenia</h2><ul><li>Vopred registrovaná štúdia sledovala veľmi veľkú skupinu z reálneho prostredia počas 12 mesiacov.</li><li>Skúmala čas do odpadnutia a výsledok overovala pri rôznych predpokladoch, nielen jedným počtom na konci roka.</li><li>Jasne určila zaradenie, odpadnutie aj povolený počet prázdnych týždňov.</li><li>Keďže je observačná, nedokazuje, že frekvencia, dĺžka tréningu alebo rozmanitosť vybavenia spôsobili dlhšie používanie.</li><li>Fitbod poskytol dáta z aplikácie a spoluautor Thiago Marzagão bol zamestnancom Fitbodu. Práca tento konflikt uvádza.</li><li>Dáta zaznamenávali pohlavie iba ako muž alebo žena a tréningová skúsenosť bola sebahodnotená. Obe voľby obmedzujú platnosť výsledkov.</li></ul><p>Štúdia ukazuje, že počiatočná pravidelnosť pomáha rozpoznať ľudí, ktorí budú denník používať dlhšie. Nevysvetľuje, prečo každý z nich pokračoval, a nevidí tréning, ktorý si nikto nezapísal.</p></section>
<section><h2>Zdroj</h2><p>Conti F, Marzagão T, Galpin AJ a Schoenfeld BJ. „Predictors of long-term resistance exercise adherence: evidence from a large cohort of mobile app users of various experience levels.“ <em>Frontiers in Sports and Active Living</em>, zverejnené 10. augusta 2026. <a href="https://doi.org/10.3389/fspor.2026.1855668">doi:10.3389/fspor.2026.1855668</a>.</p><p>Zdroj sme overili 7. októbra 2026. Recenzovaný článok je voľne dostupný pod licenciou <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. Tento článok LIFTAGu štúdiu parafrázuje a kriticky hodnotí; nepreberá jej obrázky ani tabuľky.</p></section>`,
  faqs: [
    { question: 'Čo zistila štúdia o pravidelnosti používateľov Fitbodu?', answer: 'Medzi začiatočníkmi, ktorí už počas prvých 28 dní zapisovali aspoň raz týždenne, súvisel väčší počet aktívnych dní najsilnejšie s pokračovaním v zapisovaní. Približne jeden z desiatich spĺňal pravidlo štúdie po roku. Výsledok opisuje záznamy v aplikácii a nedokazuje, že ostatní prestali cvičiť.' },
    { question: 'Znamená koniec zápisov, že človek prestal cvičiť?', answer: 'Nie nevyhnutne. Prázdny týždeň môže znamenať nulové cvičenie, ale aj inú aplikáciu, chybu importu alebo tréning bez zápisu. Štúdia merala záznamy vo Fitbode, nie všetko, čo človek robil mimo neho.' },
    { question: 'Spôsobili časté prvé tréningy dlhšiu vytrvalosť?', answer: 'Štúdia nevie dokázať príčinu a následok. Ľudia, ktorí v prvom mesiaci trénovali často, mohli mať aj viac času, motivácie, podpory alebo lepšie zdravie. Aj to mohlo vysvetliť, prečo pokračovali.' },
    { question: 'Bola štúdia nezávislá od Fitbodu?', answer: 'Fitbod poskytol dáta bez identifikačných údajov a spoluautor Thiago Marzagão pracoval pre Fitbod. Práca tento vzťah uvádza. Ostatní autori nehlásili obchodný ani finančný konflikt.' },
  ],
  ctaPath: '/',
  ctaLabel: 'Stiahnuť LIFTAG zadarmo',
  secondaryPath: '/journal/how-to-track-workouts',
  secondaryLabel: 'Ako zaznamenávať tréning',
} satisfies typeof en
