import type { JournalArticle } from './types'

export const en = {
  slug: 'why-workout-logging-habits-fade',
  path: '/journal/why-workout-logging-habits-fade',
  titleHtml: 'Why workout logging habits <span class="lime">fade.</span>',
  titleText: 'Why workout logging habits fade.',
  description:
    'A 2026 Fitbod cohort study followed app-recorded exercise for a year. Early consistency predicted longer engagement, but the study cannot tell whether people stopped training or only stopped logging.',
  seoTitle: 'Why Workout Logging Habits Fade: A 2026 Study | LIFTAG',
  datePublished: '2026-10-07',
  category: 'RESEARCH',
  dateUpdated: '2026-10',
  citations: [
    'https://www.frontiersin.org/journals/sports-and-active-living/articles/10.3389/fspor.2026.1855668/full',
    'https://doi.org/10.3389/fspor.2026.1855668',
  ],
  body: `<section><h2>The headline needs its denominator</h2><p>Federica Conti, Thiago Marzagão, Andrew J. Galpin and Brad J. Schoenfeld published a large observational study of Fitbod users in <em>Frontiers in Sports and Active Living</em> in August 2026. It asks which early behaviours are associated with continued app-recorded exercise over a year.</p><p>The full dataset contains 389,481 adults who identified as beginners, intermediate or advanced. The main adherence analysis focuses on 100,709 beginners. These were not people who downloaded an app and immediately vanished. To enter the study they had to record at least one workout in every week of their first 28 days and have a full year available for observation. The paper therefore studies people who had already cleared an initial participation threshold.</p><p>Among that selected beginner group, the estimated median time to dropout was 19 weeks and about one in ten still met the study definition at week 52. That sounds severe. The definition was also strict: at least one recorded workout per week after the first month, with up to six missed weeks allowed. A seventh empty week counted as dropout.</p></section>
<section><h2>Early consistency was the clearest signal</h2><p>The researchers measured behaviour during the first 28 days: active days, session duration, strength, cardio and mobility content, available equipment and subscription status. More active days in that opening month had the strongest association with a lower dropout hazard. The association was largest early in follow-up and weakened later.</p><p>This is useful without being a prescription. A person who trains regularly in month one may already have more time, confidence, support or motivation. The data cannot show that forcing a beginner into more sessions will create adherence. It shows that early consistency is a strong marker of the people who remain engaged.</p><p>The study also found associations with using more types of equipment and doing a larger share of resistance exercise. Longer app workouts were linked with lower dropout risk among people training more frequently, especially early on. That result cuts against the easy slogan that only short workouts are sustainable. It does not mean beginners should chase long sessions; duration was messy enough that the researchers had to cap extreme values caused by timers, duplicates or sync errors.</p></section>
<section><h2>Logging is a proxy, not the gym</h2><p>The most important sentence in the methods is that app engagement was treated as a proxy for exercise adherence. Fitbod logs included workouts made in the app and sessions imported from services such as Apple Health, Fitbit and Strava. A blank week can mean no training, but it can also mean a watch stopped syncing, someone changed apps, or a lifter trained without recording it.</p><p>That distinction matters for every workout tracker, including LIFTAG. Retention dashboards measure recorded behaviour inside a product. They do not have direct access to the person’s life. “Stopped logging” is accurate. “Stopped exercising” requires evidence the app cannot provide.</p><p>The reverse is also true. A logged workout proves an entry exists, not that every rep was completed as written. This study is stronger than a memory survey because it uses time-stamped records, but those records still contain self-entry and device artefacts.</p></section>
<section><h2>Why the first month is a special case</h2><p>The selected beginners averaged a busy opening month, with activity recorded on roughly half its days. Most also bought a paid subscription during that period. That is not the typical person casually testing a tracker. It is a cohort that had already invested attention, and often money, before follow-up began.</p><p>The study’s one-year percentage should therefore not be used as a universal probability that a new lifter will stick with training. It answers a narrower question: among Fitbod users who logged weekly for a full first month, which early patterns were associated with continuing to meet a particular logging rule?</p><p>That narrow answer is still valuable. Habit design happens before the charts become interesting. Pick a schedule that fits the week, remove friction from opening the right exercise, and make returning after a missed session ordinary. The tracker should preserve continuity without turning a broken streak into a verdict.</p></section>
<section><h2>What the paper does well—and where to stop</h2><ul><li>It follows a very large real-world cohort for twelve months and preregistered the project.</li><li>It uses survival models and sensitivity analyses rather than reducing adherence to one snapshot.</li><li>It defines inclusion, dropout and missed-week allowances precisely.</li><li>It remains observational. Associations are not proof that session frequency, duration or equipment variety caused adherence.</li><li>Fitbod provided the commercial app data, and co-author Thiago Marzagão was employed by Fitbod. The paper discloses that conflict.</li><li>The cohort requires sex to be recorded as male or female and uses self-reported experience, which limits who and what the analysis represents.</li></ul><p>The practical lesson is smaller than “train more in month one.” Build a repeatable first month and interpret app retention honestly. A tracker can reduce the effort of recording a workout. It cannot manufacture time, recovery or motivation, and it should never confuse missing data with a missing person.</p></section>
<section><h2>Source</h2><p>Conti F, Marzagão T, Galpin AJ and Schoenfeld BJ. “Predictors of long-term resistance exercise adherence: evidence from a large cohort of mobile app users of various experience levels.” <em>Frontiers in Sports and Active Living</em>, published 10 August 2026. <a href="https://doi.org/10.3389/fspor.2026.1855668">doi:10.3389/fspor.2026.1855668</a>.</p><p>Source checked 7 October 2026. The peer-reviewed article is open access under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. This LIFTAG article paraphrases and critiques the study; it does not reproduce its figures or tables.</p></section>`,
  faqs: [
    { question: 'What did the Fitbod adherence study find?', answer: 'Among selected beginners who had already logged weekly through their first 28 days, early consistency was the strongest marker of continued app-recorded activity. About one in ten met the study’s adherence definition at one year.' },
    { question: 'Does stopping workout logs mean someone stopped exercising?', answer: 'Not necessarily. A blank app week may mean no exercise, a changed app, an import failure or unlogged training. The researchers explicitly treated app engagement as a proxy for exercise adherence.' },
    { question: 'Did frequent early workouts cause people to stick with exercise?', answer: 'The study cannot establish that. It is observational. People who train frequently in the first month may differ in motivation, time, health, support and other factors that also affect later behaviour.' },
    { question: 'Was the study independent of Fitbod?', answer: 'Fitbod supplied the anonymized app data and co-author Thiago Marzagão was employed by Fitbod. The other authors declared no commercial or financial conflict, and the paper discloses the relationship.' },
  ],
  ctaPath: '/',
  ctaLabel: 'Get LIFTAG free',
  secondaryPath: '/journal/how-to-track-workouts',
  secondaryLabel: 'How to track workouts',
} satisfies JournalArticle

export const sk = {
  slug: 'why-workout-logging-habits-fade',
  path: '/journal/why-workout-logging-habits-fade',
  titleHtml: 'Prečo návyk zapisovať si tréning <span class="lime">vyprchá.</span>',
  titleText: 'Prečo návyk zapisovať si tréning vyprchá.',
  description:
    'Štúdia používateľov Fitbodu z roku 2026 sledovala zaznamenané cvičenie počas jedného roka. Pravidelnosť na začiatku predpovedala dlhšie zapojenie, no chýbajúci zápis nemusí znamenať koniec tréningu.',
  seoTitle: 'Prečo návyk zapisovať tréning vyprchá: štúdia 2026 | LIFTAG',
  datePublished: '2026-10-07',
  category: 'VÝSKUM',
  dateUpdated: '2026-10',
  citations: [
    'https://www.frontiersin.org/journals/sports-and-active-living/articles/10.3389/fspor.2026.1855668/full',
    'https://doi.org/10.3389/fspor.2026.1855668',
  ],
  body: `<section><h2>Titulok potrebuje správny menovateľ</h2><p>Federica Conti, Thiago Marzagão, Andrew J. Galpin a Brad J. Schoenfeld zverejnili v auguste 2026 v časopise <em>Frontiers in Sports and Active Living</em> veľkú observačnú štúdiu používateľov Fitbodu. Skúma, ktoré správanie na začiatku súvisí s pokračovaním v cvičení zaznamenanom aplikáciou počas jedného roka.</p><p>Celý súbor zahŕňa 389 481 dospelých, ktorí sa označili za začiatočníkov, stredne pokročilých alebo pokročilých. Hlavná analýza pravidelnosti sa sústreďuje na 100 709 začiatočníkov. Nešlo o ľudí, ktorí si aplikáciu stiahli a hneď zmizli. Do štúdie sa dostali iba vtedy, ak počas prvých 28 dní zaznamenali aspoň jeden tréning v každom týždni a výskumníci mali k dispozícii celý nasledujúci rok. Práca teda sleduje ľudí, ktorí už prekonali prvú prekážku účasti.</p><p>V tejto vybranej skupine bol odhadovaný medián času do odpadnutia 19 týždňov a približne jeden z desiatich spĺňal definíciu štúdie aj v 52. týždni. Znie to prísne a definícia prísna bola: po prvom mesiaci aspoň jeden zaznamenaný tréning týždenne, s povolenými šiestimi vynechanými týždňami. Siedmy prázdny týždeň sa počítal ako odpadnutie.</p></section>
<section><h2>Najsilnejším signálom bola pravidelnosť na začiatku</h2><p>Výskumníci merali správanie počas prvých 28 dní: aktívne dni, dĺžku tréningov, podiel silového tréningu, kardia a mobility, dostupné vybavenie aj predplatné. Viac aktívnych dní v úvodnom mesiaci malo najsilnejšiu súvislosť s nižším rizikom odpadnutia. Súvislosť bola najsilnejšia na začiatku sledovania a neskôr slabla.</p><p>Je to užitočné zistenie, nie tréningový predpis. Človek, ktorý cvičí pravidelne už v prvom mesiaci, môže mať viac času, sebadôvery, podpory alebo motivácie. Dáta nedokazujú, že keď začiatočníka prinútime k väčšiemu počtu tréningov, vytvoríme mu trvalý návyk. Ukazujú, že počiatočná pravidelnosť je silným znakom ľudí, ktorí zostanú zapojení.</p><p>Štúdia našla súvislosť aj s používaním väčšieho počtu druhov vybavenia a vyšším podielom silových cvikov. Dlhšie tréningy v aplikácii súviseli s nižším rizikom odpadnutia u ľudí, ktorí trénovali častejšie, najmä na začiatku. To nesedí s jednoduchým heslom, že udržateľné sú iba krátke tréningy. Neznamená to, že začiatočníci majú naháňať dĺžku; údaje o trvaní obsahovali extrémy zo zabudnutých časovačov, duplikátov a chýb synchronizácie, ktoré museli autori štatisticky obmedziť.</p></section>
<section><h2>Zápis je zástupný ukazovateľ, nie fitko</h2><p>Najdôležitejšia veta v metodike hovorí, že zapojenie v aplikácii bolo zástupným ukazovateľom pravidelnosti cvičenia. Záznamy Fitbodu zahŕňali tréningy vytvorené v aplikácii aj aktivity importované zo služieb ako Apple Health, Fitbit a Strava. Prázdny týždeň môže znamenať nulový tréning, ale aj pokazenú synchronizáciu hodiniek, zmenu aplikácie alebo cvičenie bez zápisu.</p><p>Tento rozdiel je dôležitý pre každý tréningový tracker vrátane LIFTAGu. Prehľady retencie merajú zaznamenané správanie v produkte. Nemajú priamy prístup k životu človeka. Tvrdenie „prestal zapisovať“ je presné. Tvrdenie „prestal cvičiť“ potrebuje dôkaz, ktorý aplikácia nemá.</p><p>Platí to aj opačne. Záznam tréningu dokazuje existenciu položky, nie to, že všetky opakovania prebehli presne podľa zápisu. Táto štúdia je silnejšia než dotazník založený na spomienkach, pretože používa záznamy s časom, no aj tie obsahujú chyby ručného vstupu a zariadení.</p></section>
<section><h2>Prečo je prvý mesiac osobitný</h2><p>Vybraní začiatočníci mali rušný úvodný mesiac a aktivitu zaznamenali približne v polovici jeho dní. Väčšina si v tomto období kúpila platené predplatné. Nie je to typický človek, ktorý si tracker iba nezáväzne skúša. Táto skupina už pred začiatkom sledovania investovala pozornosť a často aj peniaze.</p><p>Ročné percento zo štúdie preto nemožno používať ako všeobecnú pravdepodobnosť, že nový cvičenec vydrží. Odpovedá na užšiu otázku: ktoré počiatočné vzorce u používateľov Fitbodu, ktorí zapisovali každý týždeň celý prvý mesiac, súviseli s pokračovaním podľa konkrétneho pravidla?</p><p>Aj úzka odpoveď má hodnotu. Návyk vzniká skôr, než začnú byť grafy zaujímavé. Vyber rozvrh, ktorý sa zmestí do týždňa, odstráň trenie pri otvorení správneho cviku a návrat po vynechanom tréningu považuj za bežnú vec. Tracker má udržiavať kontinuitu, nie meniť prerušenú sériu na rozsudok.</p></section>
<section><h2>Čo práca robí dobre a kde sa treba zastaviť</h2><ul><li>Počas dvanástich mesiacov sleduje veľmi veľkú skupinu z reálneho sveta a projekt bol vopred registrovaný.</li><li>Používa analýzu času do udalosti a viacero kontrolných analýz namiesto jediného snímku retencie.</li><li>Presne definuje zaradenie, odpadnutie aj povolené vynechané týždne.</li><li>Zostáva observačná. Súvislosti nedokazujú, že frekvencia, dĺžka či rozmanitosť vybavenia spôsobili vytrvalosť.</li><li>Fitbod poskytol komerčné dáta a spoluautor Thiago Marzagão bol jeho zamestnancom. Práca konflikt otvorene uvádza.</li><li>Vzorka vyžadovala pohlavie uvedené ako muž alebo žena a skúsenosť bola sebahodnotená, čo obmedzuje zastúpenie ľudí aj presnosť kategórií.</li></ul><p>Praktické poučenie je menšie než „cvič v prvom mesiaci viac“. Vybuduj opakovateľný úvodný mesiac a retenciu v aplikácii vykladaj poctivo. Tracker môže znížiť námahu potrebnú na zápis. Nedokáže vyrobiť čas, regeneráciu ani motiváciu a nikdy by si nemal pomýliť chýbajúce dáta s chýbajúcim človekom.</p></section>
<section><h2>Zdroj</h2><p>Conti F, Marzagão T, Galpin AJ a Schoenfeld BJ. „Predictors of long-term resistance exercise adherence: evidence from a large cohort of mobile app users of various experience levels.“ <em>Frontiers in Sports and Active Living</em>, zverejnené 10. augusta 2026. <a href="https://doi.org/10.3389/fspor.2026.1855668">doi:10.3389/fspor.2026.1855668</a>.</p><p>Zdroj sme overili 7. októbra 2026. Recenzovaný článok je voľne dostupný pod licenciou <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. Tento článok LIFTAGu štúdiu parafrázuje a kriticky hodnotí; nepreberá jej obrázky ani tabuľky.</p></section>`,
  faqs: [
    { question: 'Čo zistila štúdia o pravidelnosti používateľov Fitbodu?', answer: 'Medzi vybranými začiatočníkmi, ktorí už počas prvých 28 dní zapisovali každý týždeň, bola počiatočná pravidelnosť najsilnejším znakom pokračovania. Približne jeden z desiatich spĺňal definíciu pravidelnosti po roku.' },
    { question: 'Znamená koniec zápisov, že človek prestal cvičiť?', answer: 'Nie nevyhnutne. Prázdny týždeň môže znamenať nulové cvičenie, inú aplikáciu, chybu importu alebo nezapísaný tréning. Autori považovali zapojenie v aplikácii iba za zástupný ukazovateľ.' },
    { question: 'Spôsobili časté prvé tréningy dlhšiu vytrvalosť?', answer: 'Štúdia to nedokáže. Je observačná. Ľudia, ktorí v prvom mesiaci trénujú často, sa môžu líšiť motiváciou, časom, zdravím či podporou, ktoré ovplyvňujú aj neskoršie správanie.' },
    { question: 'Bola štúdia nezávislá od Fitbodu?', answer: 'Fitbod poskytol anonymizované dáta a spoluautor Thiago Marzagão bol jeho zamestnancom. Ostatní autori neuviedli obchodný ani finančný konflikt a práca tento vzťah zverejňuje.' },
  ],
  ctaPath: '/',
  ctaLabel: 'Stiahnuť LIFTAG zadarmo',
  secondaryPath: '/journal/how-to-track-workouts',
  secondaryLabel: 'Ako zaznamenávať tréning',
} satisfies typeof en
